import { PrismaClient } from '@prisma/client';
import * as path from 'path';
import { loadCsvCodes } from './csv-codes';
import { loadEnglishTranslations } from './translations-en';
import { loadOemCodes } from './oem-codes';

const prisma = new PrismaClient();

const CATEGORIES = [
  { code: 'P', name: 'Powertrain (Motor y Transmisión)', description: 'Códigos relacionados con el motor, transmisión, sistema de combustible y emisiones', icon: '⚙️' },
  { code: 'B', name: 'Body (Carrocería)', description: 'Códigos relacionados con airbags, puertas, iluminación y sistemas de confort', icon: '🚗' },
  { code: 'C', name: 'Chassis (Chasis)', description: 'Códigos relacionados con frenos ABS, dirección y suspensión', icon: '🔧' },
  { code: 'U', name: 'Network (Red de Comunicación)', description: 'Códigos relacionados con el bus CAN y comunicación entre módulos', icon: '📡' },
];

// Fabricantes. El primero (isGeneric) es el centinela para códigos universales
// SAE; el resto son marcas con presencia en LatAm + US/Canadá, sembradas vacías
// y listas para recibir sus códigos específicos (P1xxx) en la Fase 3.
const MANUFACTURERS = [
  { slug: 'generico-sae', name: 'Genérico (SAE)', isGeneric: true, country: null as string | null },
  { slug: 'toyota', name: 'Toyota', isGeneric: false, country: 'Japón' },
  { slug: 'chevrolet', name: 'Chevrolet / GM', isGeneric: false, country: 'EE.UU.' },
  { slug: 'ford', name: 'Ford', isGeneric: false, country: 'EE.UU.' },
  { slug: 'nissan', name: 'Nissan', isGeneric: false, country: 'Japón' },
  { slug: 'honda', name: 'Honda', isGeneric: false, country: 'Japón' },
  { slug: 'volkswagen', name: 'Volkswagen', isGeneric: false, country: 'Alemania' },
  { slug: 'hyundai', name: 'Hyundai', isGeneric: false, country: 'Corea del Sur' },
  { slug: 'kia', name: 'Kia', isGeneric: false, country: 'Corea del Sur' },
  { slug: 'mazda', name: 'Mazda', isGeneric: false, country: 'Japón' },
  { slug: 'jeep', name: 'Jeep / Stellantis', isGeneric: false, country: 'EE.UU.' },
  { slug: 'renault', name: 'Renault', isGeneric: false, country: 'Francia' },
];

const VEHICLE_TYPES = [
  { name: 'Vehículo de Combustión Interna', type: 'ICE', brand: 'Universal', description: 'Aplica a todos los vehículos con motor de gasolina o diésel' },
  { name: 'Vehículo Eléctrico (EV)', type: 'EV', brand: 'Universal', description: 'Aplica a vehículos 100% eléctricos como Tesla, Nissan Leaf, Chevy Bolt' },
  { name: 'Vehículo Híbrido (HYBRID)', type: 'HYBRID', brand: 'Universal', description: 'Aplica a vehículos híbridos como Toyota Prius, Honda Accord Hybrid' },
];

function splitList(text: string): string[] {
  const byNumber = text.split(/\d+\.\s+/).map(s => s.trim()).filter(s => s.length > 2);
  if (byNumber.length > 1) return byNumber;
  return text.split(',').map(s => s.trim()).filter(s => s.length > 2);
}

function getVehicleCompat(code: string): string[] {
  const prefix3 = code.substring(0, 3).toUpperCase();
  if (['P0A', 'P0B', 'P0C', 'P0D'].includes(prefix3)) return ['EV', 'HYBRID'];
  return ['ICE', 'HYBRID'];
}

const ALL_CODES = [
  // ── POWERTRAIN ──────────────────────────────────────────────────────────────
  { code: 'P0100', title: 'Sensor MAF Falla - Flujo de Masa de Aire', description: 'El sensor MAF mide la cantidad de aire que entra al motor. Cuando falla, la computadora no puede calcular correctamente la mezcla aire-combustible.', symptoms: 'Ralentí inestable, Pérdida de potencia, Consumo excesivo de combustible, Dificultad para arrancar, Aceleración irregular', causes: 'Sensor MAF defectuoso, Conexiones eléctricas sueltas o corroídas, Fugas en el sistema de admisión, Filtro de aire muy sucio', solutions: '1. Limpiar el sensor MAF con limpiador específico. 2. Verificar conexiones eléctricas. 3. Revisar fugas de aire en la admisión. 4. Cambiar filtro de aire. 5. Reemplazar sensor si persiste.', severity: 'Moderada' },
  { code: 'P0101', title: 'Rango/Rendimiento Incorrecto del Sensor MAF', description: 'El sensor MAF envía señales fuera del rango esperado por la ECU, indicando lecturas incorrectas del flujo de aire.', symptoms: 'Aceleración deficiente, Humo negro del escape, Consumo elevado de gasolina, Motor ahogado', causes: 'Sensor MAF contaminado o defectuoso, Fugas de vacío, Filtro de aire obstruido, Tubo de admisión roto', solutions: '1. Limpiar el sensor MAF con limpiador electrónico. 2. Inspeccionar tubo de admisión. 3. Revisar el sistema de vacío. 4. Reemplazar sensor si es necesario.', severity: 'Moderada' },
  { code: 'P0102', title: 'Bajo Flujo de Aire en Sensor MAF', description: 'El sensor MAF detecta menos aire del esperado para las condiciones del motor.', symptoms: 'Motor lento, Aceleración débil, Dificultad para arrancar en frío', causes: 'Sensor MAF defectuoso o muy sucio, Restricción en el filtro de aire, Fuga de vacío', solutions: '1. Limpiar o reemplazar sensor MAF. 2. Cambiar filtro de aire. 3. Buscar fugas de vacío.', severity: 'Moderada' },
  { code: 'P0103', title: 'Alto Flujo de Aire en Sensor MAF', description: 'El sensor MAF reporta más aire del que debería entrar al motor.', symptoms: 'Ralentí elevado, Vibraciones del motor, Consumo excesivo', causes: 'Sensor MAF con calibración incorrecta, Fugas después del sensor MAF', solutions: '1. Reemplazar sensor MAF. 2. Reparar fugas en el sistema de admisión.', severity: 'Moderada' },
  { code: 'P0110', title: 'Sensor de Temperatura de Aire (IAT) Falla', description: 'El sensor IAT mide la temperatura del aire que entra al motor para ajustar la inyección de combustible.', symptoms: 'Ralentí inestable, Encendido difícil, Luces de advertencia encendidas', causes: 'Sensor IAT defectuoso, Conectores sueltos, Cableado dañado', solutions: '1. Limpiar conexiones. 2. Reemplazar sensor IAT.', severity: 'Moderada' },
  { code: 'P0113', title: 'Señal Alta en Sensor IAT', description: 'El sensor IAT envía señal de voltaje demasiado alta.', symptoms: 'Motor difícil de arrancar en caliente, Consumo excesivo', causes: 'Sensor IAT desconectado, Cableado abierto', solutions: '1. Revisar conector IAT. 2. Reemplazar sensor.', severity: 'Moderada' },
  { code: 'P0115', title: 'Sensor de Temperatura del Refrigerante (ECT) Falla', description: 'El sensor ECT mide la temperatura del motor. Su falla afecta la inyección de combustible y encendido.', symptoms: 'Ralentí anormal, Consumo excesivo, Arranque difícil', causes: 'Sensor ECT defectuoso, Conectores sueltos, Corrosión', solutions: '1. Limpiar conectores. 2. Reemplazar sensor ECT.', severity: 'Moderada' },
  { code: 'P0116', title: 'Rango Incorrecto Sensor ECT', description: 'El sensor de temperatura del refrigerante envía señales fuera del rango esperado.', symptoms: 'Temperatura del motor incorrecta en tablero, Consumo alto', causes: 'Sensor ECT descalibrado, Termostato dañado', solutions: '1. Reemplazar sensor ECT. 2. Verificar termostato.', severity: 'Moderada' },
  { code: 'P0120', title: 'Sensor Posición del Acelerador (TPS) Falla', description: 'El sensor TPS monitorea la apertura del acelerador. Su falla afecta la respuesta del motor.', symptoms: 'Aceleración errabunda, Ralentí variable, Motor tembloroso', causes: 'Sensor TPS defectuoso, Conexiones sueltas, Suciedad en acelerador', solutions: '1. Limpiar acelerador. 2. Calibrar TPS. 3. Reemplazar sensor.', severity: 'Moderada' },
  { code: 'P0121', title: 'Rango/Rendimiento de Sensor TPS Incorrecto', description: 'Lecturas del sensor TPS fuera del rango normal.', symptoms: 'Aceleración lenta o errabunda, Dificultad en cambios', causes: 'Sensor descalibrado, Falla eléctrica en TPS', solutions: '1. Recalibrar TPS. 2. Reemplazar sensor.', severity: 'Moderada' },
  { code: 'P0130', title: 'Falla del Sensor de Oxígeno O2 Banco 1 Sensor 1', description: 'El sensor O2 frontal mide oxígeno residual en el escape para ajustar la mezcla aire-combustible.', symptoms: 'Luz Check Engine, Consumo excesivo, Ralentí inestable', causes: 'Sensor O2 degradado, Conexiones sueltas, Escape dañado', solutions: '1. Limpiar conexiones. 2. Reemplazar sensor O2.', severity: 'Moderada' },
  { code: 'P0131', title: 'Voltaje Bajo Sensor O2 Banco 1', description: 'El voltaje del sensor O2 es anormalmente bajo, indicando mezcla pobre.', symptoms: 'Mezcla pobre, Pérdida de potencia, Humo blanco del escape', causes: 'Sensor O2 débil o defectuoso, Cableado abierto', solutions: '1. Reemplazar sensor O2.', severity: 'Moderada' },
  { code: 'P0132', title: 'Voltaje Alto Sensor O2 Banco 1', description: 'El voltaje del sensor O2 es anormalmente alto, indicando mezcla rica.', symptoms: 'Humo negro del escape, Consumo excesivo, Olor a gasolina', causes: 'Sensor con mala conexión a tierra, Circuito en cortocircuito', solutions: '1. Reparar conexión a tierra. 2. Reemplazar sensor.', severity: 'Moderada' },
  { code: 'P0133', title: 'Respuesta Lenta del Sensor O2 Banco 1', description: 'El sensor O2 tarda demasiado en cambiar de voltaje, afectando el ajuste de mezcla.', symptoms: 'Encendido lento, Ralentí irregular, Consumo variable', causes: 'Sensor O2 envejecido, Escape sucio con depósitos', solutions: '1. Limpiar sensor. 2. Reemplazar si es viejo.', severity: 'Moderada' },
  { code: 'P0134', title: 'Sin Actividad en Sensor O2 Banco 1', description: 'El sensor O2 no muestra variación de voltaje, indica sensor muerto.', symptoms: 'Luz Check Engine constante, Consumo elevado', causes: 'Sensor O2 muerto, Cableado cortado', solutions: '1. Reemplazar sensor O2.', severity: 'Moderada' },
  { code: 'P0135', title: 'Calefactor del Sensor O2 Banco 1 Falla', description: 'El elemento calefactor del sensor O2 no funciona, retrasando su entrada en operación.', symptoms: 'Sensor O2 lento para calentar, Ralentí anormal al arrancar', causes: 'Elemento calefactor quemado, Conexiones sueltas', solutions: '1. Reemplazar sensor O2 completo.', severity: 'Moderada' },
  { code: 'P0136', title: 'Falla Sensor O2 Banco 1 Sensor 2 (Post-catalizador)', description: 'El sensor O2 que mide la eficiencia del catalizador no funciona correctamente.', symptoms: 'Luz Check Engine, No pasa prueba de emisiones', causes: 'Sensor O2 downstream defectuoso, Catalizador dañado', solutions: '1. Reemplazar sensor O2 post-catalizador. 2. Revisar catalizador.', severity: 'Moderada' },
  { code: 'P0137', title: 'Voltaje Bajo Sensor O2 Banco 1 Sensor 2', description: 'Voltaje bajo en sensor O2 después del catalizador.', symptoms: 'Emisiones altas, Luz Check Engine', causes: 'Sensor O2 defectuoso, Fuga de escape', solutions: '1. Reemplazar sensor O2.', severity: 'Moderada' },
  { code: 'P0138', title: 'Voltaje Alto Sensor O2 Banco 1 Sensor 2', description: 'Voltaje alto en sensor O2 después del catalizador.', symptoms: 'Emisiones altas, Luz Check Engine', causes: 'Sensor defectuoso, Cortocircuito', solutions: '1. Reemplazar sensor O2.', severity: 'Moderada' },
  { code: 'P0141', title: 'Calefactor Sensor O2 Banco 1 Sensor 2 Falla', description: 'El calefactor del sensor O2 post-catalizador no funciona.', symptoms: 'Sensor O2 lento para operar, Luz Check Engine', causes: 'Calefactor quemado', solutions: '1. Reemplazar sensor O2.', severity: 'Moderada' },
  { code: 'P0150', title: 'Falla Sensor O2 Banco 2 Sensor 1', description: 'El sensor O2 frontal del banco 2 no funciona correctamente.', symptoms: 'Mezcla desequilibrada banco 2, Consumo elevado', causes: 'Sensor O2 banco 2 defectuoso', solutions: '1. Reemplazar sensor O2 banco 2.', severity: 'Moderada' },
  { code: 'P0155', title: 'Calefactor Sensor O2 Banco 2 Sensor 1 Falla', description: 'Calefactor del sensor O2 frontal banco 2 no funciona.', symptoms: 'Ralentí anormal al inicio, Consumo elevado', causes: 'Calefactor quemado', solutions: '1. Reemplazar sensor O2.', severity: 'Moderada' },
  { code: 'P0171', title: 'Mezcla de Combustible Demasiado Pobre Banco 1', description: 'La computadora detecta que hay demasiado aire y poco combustible en la mezcla del banco 1.', symptoms: 'Ralentí irregular, Dificultad para acelerar, Explosiones en escape, Pérdida de potencia en subidas', causes: 'Fuga de vacío en la admisión, Sensor MAF sucio, Bomba de combustible débil, Inyectores obstruidos, Filtro de combustible tapado', solutions: '1. Buscar fugas de vacío con spray. 2. Limpiar o reemplazar sensor MAF. 3. Verificar presión de combustible. 4. Limpiar inyectores.', severity: 'Moderada' },
  { code: 'P0172', title: 'Mezcla de Combustible Demasiado Rica Banco 1', description: 'La computadora detecta exceso de combustible en relación al aire en el banco 1.', symptoms: 'Humo negro del escape, Olor fuerte a gasolina, Consumo excesivo, Bujías negras con hollín', causes: 'Inyectores con fugas internas, Regulador de presión defectuoso, Sensor de oxígeno malo, Filtro de aire muy sucio', solutions: '1. Verificar inyectores (prueba de goteo). 2. Revisar regulador de presión de combustible. 3. Reemplazar sensor O2 si es necesario. 4. Cambiar filtro de aire.', severity: 'Moderada' },
  { code: 'P0174', title: 'Mezcla de Combustible Demasiado Pobre Banco 2', description: 'Similar a P0171 pero para el banco 2 del motor.', symptoms: 'Ralentí irregular banco 2, Pérdida de potencia', causes: 'Fugas de vacío banco 2, Sensor MAF sucio', solutions: '1. Revisar fugas de vacío banco 2. 2. Limpiar sensor MAF.', severity: 'Moderada' },
  { code: 'P0175', title: 'Mezcla de Combustible Demasiado Rica Banco 2', description: 'Similar a P0172 pero para el banco 2 del motor.', symptoms: 'Humo negro, Consumo excesivo banco 2', causes: 'Inyectores banco 2 con fugas', solutions: '1. Verificar inyectores banco 2.', severity: 'Moderada' },
  { code: 'P0200', title: 'Falla General en Circuito de Inyectores', description: 'Problema general en el circuito de inyectores de combustible.', symptoms: 'Motor tembloroso, Arranque difícil, Pérdida de potencia general', causes: 'Relé de inyectores defectuoso, Fusible quemado, Cableado general dañado', solutions: '1. Verificar fusible de inyectores. 2. Probar relé. 3. Revisar cableado.', severity: 'Moderada' },
  { code: 'P0201', title: 'Circuito Inyector Cilindro 1 Falla', description: 'El inyector del cilindro 1 no funciona correctamente.', symptoms: 'Motor tembloroso, Falta de potencia, Vibración en cilindro 1', causes: 'Inyector obstruido o defectuoso cilindro 1, Cableado dañado', solutions: '1. Limpiar o reemplazar inyector cilindro 1.', severity: 'Moderada' },
  { code: 'P0202', title: 'Circuito Inyector Cilindro 2 Falla', description: 'El inyector del cilindro 2 no funciona correctamente.', symptoms: 'Motor tembloroso, Vibración en cilindro 2', causes: 'Inyector cilindro 2 defectuoso', solutions: '1. Limpiar o reemplazar inyector cilindro 2.', severity: 'Moderada' },
  { code: 'P0203', title: 'Circuito Inyector Cilindro 3 Falla', description: 'El inyector del cilindro 3 no funciona correctamente.', symptoms: 'Motor tembloroso, Vibración en cilindro 3', causes: 'Inyector cilindro 3 defectuoso', solutions: '1. Limpiar o reemplazar inyector cilindro 3.', severity: 'Moderada' },
  { code: 'P0204', title: 'Circuito Inyector Cilindro 4 Falla', description: 'El inyector del cilindro 4 no funciona correctamente.', symptoms: 'Motor tembloroso, Vibración en cilindro 4', causes: 'Inyector cilindro 4 defectuoso', solutions: '1. Limpiar o reemplazar inyector cilindro 4.', severity: 'Moderada' },
  { code: 'P0205', title: 'Circuito Inyector Cilindro 5 Falla', description: 'El inyector del cilindro 5 no funciona correctamente.', symptoms: 'Motor tembloroso, Vibración en cilindro 5', causes: 'Inyector cilindro 5 defectuoso', solutions: '1. Limpiar o reemplazar inyector cilindro 5.', severity: 'Moderada' },
  { code: 'P0206', title: 'Circuito Inyector Cilindro 6 Falla', description: 'El inyector del cilindro 6 no funciona correctamente.', symptoms: 'Motor tembloroso, Vibración en cilindro 6', causes: 'Inyector cilindro 6 defectuoso', solutions: '1. Limpiar o reemplazar inyector cilindro 6.', severity: 'Moderada' },
  { code: 'P0300', title: 'Fallo de Encendido Aleatorio en Múltiples Cilindros', description: 'Se detectan fallos de encendido en varios cilindros sin patrón definido. Puede dañar el catalizador.', symptoms: 'Motor tembloroso, Pérdida notable de potencia, Luz Check Engine parpadeando, Vibraciones al acelerar, Explosiones en el escape', causes: 'Bujías desgastadas, Cables de bujía defectuosos, Bobinas de encendido fallando, Inyectores sucios, Baja compresión', solutions: '1. Revisar y reemplazar bujías. 2. Verificar cables de alta tensión. 3. Probar bobinas de encendido. 4. Limpiar o reemplazar inyectores. 5. Realizar prueba de compresión.', severity: 'Crítica/No conducir' },
  { code: 'P0301', title: 'Fallo de Encendido en Cilindro 1', description: 'El cilindro número 1 no está realizando la combustión correctamente.', symptoms: 'Vibración del motor, Pérdida de potencia, Consumo irregular, Luz Check Engine parpadeando', causes: 'Bujía del cilindro 1 defectuosa, Bobina de encendido dañada, Inyector obstruido, Baja compresión en cilindro 1', solutions: '1. Reemplazar bujía del cilindro 1. 2. Probar bobina con multímetro. 3. Verificar inyector. 4. Medir compresión.', severity: 'Crítica/No conducir' },
  { code: 'P0302', title: 'Fallo de Encendido en Cilindro 2', description: 'El cilindro 2 no combustiona correctamente.', symptoms: 'Vibración del motor, Pérdida de potencia en cilindro 2', causes: 'Bujía cilindro 2 defectuosa, Bobina de encendido dañada', solutions: '1. Reemplazar bujía cilindro 2. 2. Probar bobina.', severity: 'Crítica/No conducir' },
  { code: 'P0303', title: 'Fallo de Encendido en Cilindro 3', description: 'El cilindro 3 no combustiona correctamente.', symptoms: 'Vibración del motor, Pérdida de potencia en cilindro 3', causes: 'Bujía cilindro 3 defectuosa, Bobina de encendido dañada', solutions: '1. Reemplazar bujía cilindro 3. 2. Probar bobina.', severity: 'Crítica/No conducir' },
  { code: 'P0304', title: 'Fallo de Encendido en Cilindro 4', description: 'El cilindro 4 no combustiona correctamente.', symptoms: 'Vibración del motor, Pérdida de potencia en cilindro 4', causes: 'Bujía cilindro 4 defectuosa, Bobina de encendido dañada', solutions: '1. Reemplazar bujía cilindro 4. 2. Probar bobina.', severity: 'Crítica/No conducir' },
  { code: 'P0305', title: 'Fallo de Encendido en Cilindro 5', description: 'El cilindro 5 no combustiona correctamente.', symptoms: 'Vibración del motor, Pérdida de potencia en cilindro 5', causes: 'Bujía cilindro 5 defectuosa', solutions: '1. Reemplazar bujía cilindro 5.', severity: 'Crítica/No conducir' },
  { code: 'P0306', title: 'Fallo de Encendido en Cilindro 6', description: 'El cilindro 6 no combustiona correctamente.', symptoms: 'Vibración del motor, Pérdida de potencia en cilindro 6', causes: 'Bujía cilindro 6 defectuosa', solutions: '1. Reemplazar bujía cilindro 6.', severity: 'Crítica/No conducir' },
  { code: 'P0307', title: 'Fallo de Encendido en Cilindro 7', description: 'El cilindro 7 no combustiona correctamente.', symptoms: 'Vibración del motor, Pérdida de potencia', causes: 'Bujía cilindro 7 defectuosa', solutions: '1. Reemplazar bujía cilindro 7.', severity: 'Crítica/No conducir' },
  { code: 'P0308', title: 'Fallo de Encendido en Cilindro 8', description: 'El cilindro 8 no combustiona correctamente.', symptoms: 'Vibración del motor, Pérdida de potencia', causes: 'Bujía cilindro 8 defectuosa', solutions: '1. Reemplazar bujía cilindro 8.', severity: 'Crítica/No conducir' },
  { code: 'P0316', title: 'Fallo de Encendido al Arrancar', description: 'Se detectan fallos de encendido específicamente durante el arranque del motor.', symptoms: 'Arranque brusco, Vibraciones al encender, Humo del escape al arrancar', causes: 'Bujías frías defectuosas, Bobinas débiles, Inyectores sucios', solutions: '1. Reemplazar bujías. 2. Probar bobinas. 3. Limpiar inyectores.', severity: 'Moderada' },
  { code: 'P0340', title: 'Sensor de Posición del Árbol de Levas Banco 1 Falla', description: 'El sensor CMP no envía señal correcta, afectando la sincronización del motor.', symptoms: 'No arranca o arranca difícil, Motor se detiene al conducir', causes: 'Sensor CMP defectuoso, Cableado dañado, Rueda fónica sucia', solutions: '1. Limpiar sensor CMP. 2. Verificar cableado. 3. Reemplazar sensor.', severity: 'Crítica/No conducir' },
  { code: 'P0335', title: 'Sensor de Posición del Cigüeñal (CKP) Falla', description: 'El sensor del cigüeñal es crítico para el funcionamiento del motor. Sin esta señal el motor no arranca.', symptoms: 'No arranca, Motor se detiene inesperadamente, Pérdida total de encendido', causes: 'Sensor CKP defectuoso, Cableado cortado, Rueda fónica dañada', solutions: '1. Limpiar área del sensor. 2. Verificar cableado. 3. Reemplazar sensor CKP.', severity: 'Crítica/No conducir' },
  { code: 'P0336', title: 'Rango/Rendimiento Sensor CKP', description: 'El sensor del cigüeñal envía señal errática.', symptoms: 'Motor irregular, Arranque difícil', causes: 'Sensor CKP contaminado, Rueda fónica con dientes dañados', solutions: '1. Limpiar sensor. 2. Inspeccionar rueda fónica.', severity: 'Crítica/No conducir' },
  { code: 'P0400', title: 'Falla General Sistema EGR', description: 'El sistema de recirculación de gases de escape (EGR) tiene un problema general.', symptoms: 'Luz Check Engine, Detonación en motor, Emisiones altas', causes: 'Válvula EGR obstruida, Solenoide defectuoso, Sensor EGR falla', solutions: '1. Limpiar válvula EGR. 2. Verificar solenoide. 3. Revisar sensor EGR.', severity: 'Baja' },
  { code: 'P0401', title: 'Flujo Insuficiente en Sistema EGR', description: 'El sistema EGR no circula suficientes gases de escape. Aumenta las emisiones de NOx.', symptoms: 'Golpeteo del motor, Aumento de emisiones, Rendimiento reducido a baja velocidad', causes: 'Válvula EGR obstruida con carbón, Conductos de EGR tapados, Sensor de posición EGR defectuoso, Solenoide EGR dañado', solutions: '1. Limpiar válvula EGR con limpiador de carburador. 2. Limpiar conductos de recirculación. 3. Verificar funcionamiento del solenoide. 4. Reemplazar válvula si es necesario.', severity: 'Baja' },
  { code: 'P0402', title: 'Flujo Excesivo en Sistema EGR', description: 'El flujo EGR es demasiado alto, causando mezcla excesiva.', symptoms: 'Ralentí inestable, Arranque difícil, Pérdida de potencia', causes: 'Válvula EGR pegada abierta, Sensor defectuoso', solutions: '1. Limpiar y calibrar válvula EGR.', severity: 'Baja' },
  { code: 'P0403', title: 'Circuito Solenoide EGR Falla', description: 'El solenoide que controla la válvula EGR no funciona correctamente.', symptoms: 'Válvula EGR no responde, Luz Check Engine', causes: 'Solenoide EGR dañado, Cableado suelto', solutions: '1. Reemplazar solenoide EGR.', severity: 'Baja' },
  { code: 'P0420', title: 'Eficiencia Baja del Convertidor Catalítico Banco 1', description: 'El convertidor catalítico no está limpiando los gases de escape eficientemente. Los sensores O2 upstream/downstream tienen lecturas similares.', symptoms: 'Luz Check Engine encendida, Posible olor a azufre, Fallo en prueba de emisiones, Pérdida leve de potencia', causes: 'Convertidor catalítico deteriorado o dañado, Sensor de oxígeno defectuoso, Fugas en el sistema de escape', solutions: '1. Verificar sensores de oxígeno con escáner. 2. Inspeccionar fugas en el escape. 3. Probar eficiencia del catalizador. 4. Reemplazar convertidor catalítico si es necesario.', severity: 'Moderada' },
  { code: 'P0421', title: 'Eficiencia Baja del Catalizador Banco 1 (Sistema de Calentamiento)', description: 'El catalizador no alcanza temperatura de operación correctamente.', symptoms: 'Emisiones altas en frío, Olor a azufre', causes: 'Catalizador con desgaste severo', solutions: '1. Reemplazar catalizador banco 1.', severity: 'Moderada' },
  { code: 'P0430', title: 'Eficiencia Baja del Convertidor Catalítico Banco 2', description: 'El catalizador del banco 2 no limpia correctamente los gases de escape.', symptoms: 'Olor a azufre, Emisiones altas, Fallo prueba de emisiones', causes: 'Catalizador banco 2 deteriorado, Sensor O2 defectuoso', solutions: '1. Reemplazar catalizador banco 2.', severity: 'Moderada' },
  { code: 'P0440', title: 'Falla General en Sistema EVAP', description: 'El sistema de captura de vapores de combustible tiene problemas generales.', symptoms: 'Luz Check Engine, Olor leve a gasolina', causes: 'Tapa de combustible suelta, Mangueras rotas, Válvula de purga obstruida', solutions: '1. Apretar o reemplazar tapa de combustible. 2. Inspeccionar mangueras EVAP.', severity: 'Baja' },
  { code: 'P0441', title: 'Flujo Incorrecto en Sistema EVAP', description: 'Flujo de vapores de combustible incorrecto en el sistema EVAP.', symptoms: 'Olor a gasolina, Luz Check Engine', causes: 'Válvula de purga defectuosa, Manguera obstruida', solutions: '1. Limpiar o reemplazar válvula de purga.', severity: 'Baja' },
  { code: 'P0442', title: 'Fuga Pequeña en Sistema EVAP', description: 'Se detectó una fuga menor en el sistema de control de emisiones evaporativas.', symptoms: 'Luz Check Engine encendida, Posible olor leve a gasolina, Sin síntomas de manejo', causes: 'Tapa del tanque floja o dañada, Mangueras EVAP agrietadas, Válvula de purga con fuga pequeña', solutions: '1. Apretar o reemplazar la tapa de combustible. 2. Inspeccionar mangueras del sistema EVAP. 3. Realizar prueba de humo para encontrar la fuga.', severity: 'Baja' },
  { code: 'P0443', title: 'Circuito Válvula de Purga EVAP Falla', description: 'El circuito de la válvula de purga del sistema EVAP tiene problemas.', symptoms: 'Olor a gasolina, Luz Check Engine', causes: 'Válvula de purga dañada, Cableado suelto', solutions: '1. Reparar cableado. 2. Reemplazar válvula de purga.', severity: 'Baja' },
  { code: 'P0446', title: 'Circuito Válvula de Ventilación EVAP Falla', description: 'La válvula de ventilación del sistema EVAP tiene problemas.', symptoms: 'Olor a gasolina, Luz Check Engine', causes: 'Válvula defectuosa, Canister de carbón activo bloqueado', solutions: '1. Reemplazar válvula de ventilación. 2. Inspeccionar canister.', severity: 'Baja' },
  { code: 'P0455', title: 'Fuga Grande en Sistema EVAP', description: 'Existe una fuga significativa en el sistema EVAP.', symptoms: 'Luz Check Engine encendida, Olor notable a gasolina, Posible dificultad para llenar el tanque', causes: 'Tapa de combustible faltante o muy dañada, Manguera EVAP desconectada, Tanque de carbón activado roto', solutions: '1. Verificar que la tapa esté puesta correctamente. 2. Inspeccionar visualmente todas las mangueras EVAP. 3. Revisar canister de carbón activado.', severity: 'Baja' },
  { code: 'P0456', title: 'Fuga Muy Pequeña en Sistema EVAP', description: 'Se detectó una fuga muy pequeña en el sistema EVAP.', symptoms: 'Luz Check Engine, Olor muy leve a combustible', causes: 'Pequeña fuga en tuberías o conectores EVAP', solutions: '1. Inspeccionar sistema completo con prueba de humo.', severity: 'Baja' },
  { code: 'P0457', title: 'Tapa de Combustible Floja en Sistema EVAP', description: 'La tapa del tanque de combustible está floja o mal puesta.', symptoms: 'Luz Check Engine, Olor a gasolina', causes: 'Tapa de combustible suelta o dañada', solutions: '1. Apretar firmemente la tapa. 2. Reemplazar tapa si está dañada.', severity: 'Baja' },
  { code: 'P0460', title: 'Sensor de Nivel de Combustible Falla', description: 'El sensor de nivel de combustible envía señal incorrecta.', symptoms: 'Indicador de combustible incorrecto, Luz de combustible bajo erróneamente encendida', causes: 'Sensor de nivel defectuoso, Flotador del tanque dañado', solutions: '1. Inspeccionar sensor de nivel. 2. Reemplazar flotador.', severity: 'Baja' },
  { code: 'P0480', title: 'Circuito Relé del Ventilador de Enfriamiento Falla', description: 'El relé que controla el ventilador de enfriamiento del motor no funciona.', symptoms: 'Motor se sobrecalienta, Ventilador no enciende, A/C ineficiente', causes: 'Relé del ventilador dañado, Cableado suelto, Fusible quemado', solutions: '1. Reemplazar relé del ventilador. 2. Verificar fusible.', severity: 'Crítica/No conducir' },
  { code: 'P0481', title: 'Circuito Relé del Ventilador de Velocidad Media Falla', description: 'El ventilador de enfriamiento en velocidad media no funciona.', symptoms: 'Motor en temperatura ligeramente alta, Ventilador no opera en velocidad media', causes: 'Relé velocidad media dañado, Cableado defectuoso', solutions: '1. Reemplazar relé de velocidad media.', severity: 'Moderada' },
  { code: 'P0500', title: 'Falla del Sensor de Velocidad del Vehículo (VSS)', description: 'El sensor que mide la velocidad del vehículo no envía señal correcta.', symptoms: 'Velocímetro no funciona o marca incorrectamente, Cambios erráticos de transmisión, Luz ABS encendida', causes: 'Sensor VSS defectuoso, Cableado dañado, Conector corroído, Problemas en el piñón del sensor', solutions: '1. Reemplazar sensor de velocidad. 2. Verificar cableado y conectores. 3. Limpiar conexiones. 4. Revisar el piñón del sensor.', severity: 'Moderada' },
  { code: 'P0501', title: 'Rango/Rendimiento Sensor VSS', description: 'El sensor de velocidad envía señal fuera de rango.', symptoms: 'Velocímetro incorrecto, Transmisión con cambios irregulares', causes: 'Sensor VSS descalibrado, Interferencia magnética', solutions: '1. Reemplazar sensor VSS.', severity: 'Moderada' },
  { code: 'P0505', title: 'Sistema de Control de Ralentí Falla', description: 'El motor no mantiene un ralentí correcto y estable.', symptoms: 'Ralentí muy alto o muy bajo, Vibración al ralentí, Motor casi se apaga', causes: 'Sensor IAC defectuoso, Fuga de vacío, Acelerador sucio', solutions: '1. Limpiar sensor IAC. 2. Buscar fugas de vacío. 3. Limpiar acelerador.', severity: 'Moderada' },
  { code: 'P0506', title: 'RPM de Ralentí Demasiado Bajas', description: 'El motor funciona con ralentí más bajo de lo normal del rango programado.', symptoms: 'Ralentí muy bajo, Motor casi se apaga, Vibración fuerte', causes: 'Fuga de aire, Sensor MAF sucio, Controlador defectuoso', solutions: '1. Buscar fugas de aire. 2. Limpiar sensor MAF.', severity: 'Moderada' },
  { code: 'P0507', title: 'RPM de Ralentí Demasiado Altas', description: 'El motor funciona con ralentí más alto de lo normal.', symptoms: 'Ralentí muy elevado, Consumo excesivo en marcha', causes: 'Fuga de aire después del sensor MAF, Termostato atascado, IAC pegado abierto', solutions: '1. Buscar fugas de aire. 2. Revisar termostato. 3. Limpiar IAC.', severity: 'Moderada' },
  { code: 'P0520', title: 'Sensor de Presión de Aceite del Motor Falla', description: 'El sensor de presión de aceite no está funcionando correctamente.', symptoms: 'Luz de aceite encendida de forma errónica, Sin lectura de presión de aceite', causes: 'Sensor de presión de aceite defectuoso, Cableado dañado', solutions: '1. Reemplazar sensor de presión de aceite. 2. Verificar nivel de aceite real.', severity: 'Moderada' },
  { code: 'P0521', title: 'Rango Incorrecto del Sensor de Presión de Aceite', description: 'El sensor de presión de aceite envía señal fuera de rango.', symptoms: 'Lectura de presión errática, Luz de aceite intermitente', causes: 'Sensor descalibrado, Bajo nivel de aceite real', solutions: '1. Verificar nivel de aceite. 2. Reemplazar sensor.', severity: 'Moderada' },
  { code: 'P0560', title: 'Voltaje del Sistema Eléctrico Bajo General', description: 'Problema general detectado en el voltaje del sistema eléctrico del vehículo.', symptoms: 'Luz de batería encendida, Arranque débil, Accesorios con poco voltaje', causes: 'Batería baja, Alternador defectuoso, Conexiones corroídas', solutions: '1. Revisar batería. 2. Probar alternador.', severity: 'Moderada' },
  { code: 'P0562', title: 'Voltaje del Sistema Eléctrico Demasiado Bajo', description: 'Voltaje del sistema eléctrico menor a 10V durante operación normal.', symptoms: 'Arranque débil o no arranca, Luz de batería encendida', causes: 'Batería descargada, Alternador no carga, Conexión negativa floja', solutions: '1. Cargar batería. 2. Revisar alternador. 3. Limpiar conexiones de batería.', severity: 'Moderada' },
  { code: 'P0563', title: 'Voltaje del Sistema Eléctrico Demasiado Alto', description: 'Voltaje del sistema eléctrico mayor a 16V.', symptoms: 'Quemado de componentes electrónicos, Luces muy brillantes', causes: 'Regulador de voltaje del alternador defectuoso', solutions: '1. Reemplazar regulador. 2. Revisar alternador.', severity: 'Moderada' },
  { code: 'P0600', title: 'Falla de Comunicación de la Computadora Principal', description: 'Problema de comunicación interna en la ECU principal del vehículo.', symptoms: 'Múltiples códigos de error, Muchas luces de advertencia encendidas', causes: 'ECU defectuosa, Problemas de comunicación interna', solutions: '1. Escaneo completo del sistema. 2. Reemplazar ECU.', severity: 'Crítica/No conducir' },
  { code: 'P0601', title: 'Error de Memoria ROM en ECU', description: 'Error de checksum en la memoria ROM de la ECU.', symptoms: 'Luz Check Engine, Funcionamiento anormal del motor', causes: 'ECU defectuosa, Memoria dañada', solutions: '1. Reemplazar ECU o reprogramar.', severity: 'Crítica/No conducir' },
  { code: 'P0602', title: 'Programación de ECU Defectuosa o Incompleta', description: 'El programa de la ECU está corrupto o incompleto.', symptoms: 'No arranca o arranca mal, Múltiples códigos', causes: 'ECU con programa defectuoso', solutions: '1. Reprogramar ECU con software actualizado.', severity: 'Crítica/No conducir' },
  { code: 'P0603', title: 'Error en Memoria KAM de la ECU', description: 'Error en la memoria de acceso de llave (Keep Alive Memory) de la ECU.', symptoms: 'Reajuste de configuraciones del motor, Comportamiento inestable', causes: 'ECU defectuosa, Desconexión de batería', solutions: '1. Conectar batería cargada. 2. Reemplazar ECU si persiste.', severity: 'Moderada' },
  { code: 'P0606', title: 'Procesador de ECU Defectuoso', description: 'El procesador principal de la ECU está dañado.', symptoms: 'No arranca o arranca muy mal, Sistema inestable', causes: 'ECU defectuosa, Daño por sobrevoltaje', solutions: '1. Reemplazar ECU.', severity: 'Crítica/No conducir' },
  { code: 'P0620', title: 'Falla General del Alternador', description: 'El alternador no funciona correctamente, afectando la carga de la batería.', symptoms: 'Luz de batería encendida, Arranque débil, Pérdida de carga progresiva', causes: 'Alternador defectuoso, Conexiones sueltas, Correas desgastadas', solutions: '1. Revisar correas del alternador. 2. Probar alternador. 3. Reemplazar si es necesario.', severity: 'Moderada' },
  { code: 'P0700', title: 'Falla General del Sistema de Transmisión Automática', description: 'La computadora del motor detectó que hay un problema en el módulo de control de la transmisión.', symptoms: 'Luz de transmisión encendida, Cambios bruscos o tardíos, Transmisión en modo limp mode, No pasa de segunda', causes: 'Problema interno en la transmisión, Módulo TCM defectuoso, Bajo nivel de fluido, Solenoide de cambio dañado', solutions: '1. Verificar nivel y estado del fluido de transmisión. 2. Escanear módulo TCM para códigos específicos. 3. Revisar solenoides. 4. Llevar con especialista en transmisiones.', severity: 'Crítica/No conducir' },
  { code: 'P0705', title: 'Sensor de Rango de Transmisión Falla', description: 'El sensor que detecta la posición del selector de transmisión falla.', symptoms: 'Luz de transmisión, Cambios en posición incorrecta', causes: 'Sensor de rango/posición defectuoso, Conector suelto', solutions: '1. Limpiar conexiones. 2. Reemplazar sensor de rango.', severity: 'Moderada' },
  { code: 'P0715', title: 'Sensor de Velocidad de Entrada de Transmisión Falla', description: 'El sensor de RPM de la entrada de transmisión falla.', symptoms: 'Cambios anormales, Pérdida de marchas específicas', causes: 'Sensor de velocidad de entrada defectuoso, Conector suelto', solutions: '1. Limpiar conexiones. 2. Reemplazar sensor.', severity: 'Moderada' },
  { code: 'P0720', title: 'Sensor de Velocidad de Salida de Transmisión Falla', description: 'El sensor de velocidad de salida de la transmisión falla.', symptoms: 'Velocímetro no funciona correctamente, Cambios anormales', causes: 'Sensor VSS de transmisión defectuoso', solutions: '1. Reemplazar sensor de velocidad de salida.', severity: 'Moderada' },
  { code: 'P0730', title: 'Rango Incorrecto de Transmisión', description: 'La transmisión no puede encontrar la marcha correcta.', symptoms: 'Cambios anormales, Luz de transmisión, Resbalamiento', causes: 'Sensor de rango defectuoso, Módulo TCM defectuoso', solutions: '1. Revisar sensor de rango. 2. Escanear TCM.', severity: 'Moderada' },
  { code: 'P0740', title: 'Circuito Solenoide del Convertidor de Par Falla', description: 'Problema en el solenoide del convertidor de par de la transmisión automática.', symptoms: 'Pérdida de eficiencia en carretera, Cambios anormales', causes: 'Solenoide del convertidor de par defectuoso, Cableado suelto', solutions: '1. Reparar cableado. 2. Reemplazar solenoide.', severity: 'Moderada' },
  { code: 'P0741', title: 'Solenoide del Convertidor de Par en Modo Abierto o Cerrado', description: 'El solenoide del convertidor de par está atascado.', symptoms: 'Motor trabado al frenar, Consumo alto en carretera', causes: 'Solenoide pegado, Fluido de transmisión sucio', solutions: '1. Cambiar fluido de transmisión. 2. Reemplazar solenoide.', severity: 'Moderada' },
  { code: 'P0750', title: 'Solenoide de Cambio A Falla', description: 'El solenoide A de cambio de la transmisión no funciona.', symptoms: 'Transmisión en modo de emergencia, Cambios anormales', causes: 'Solenoide A defectuoso, Fluido bajo', solutions: '1. Verificar fluido. 2. Reemplazar solenoide A.', severity: 'Moderada' },
  { code: 'P0755', title: 'Solenoide de Cambio B Falla', description: 'El solenoide B de cambio de la transmisión no funciona.', symptoms: 'Transmisión en modo de emergencia, Cambios anormales', causes: 'Solenoide B defectuoso, Fluido bajo', solutions: '1. Verificar fluido. 2. Reemplazar solenoide B.', severity: 'Moderada' },
  { code: 'P0760', title: 'Solenoide de Cambio C Falla', description: 'El solenoide C de cambio de la transmisión no funciona.', symptoms: 'Transmisión en modo de emergencia', causes: 'Solenoide C defectuoso', solutions: '1. Reemplazar solenoide C.', severity: 'Moderada' },
  { code: 'P0765', title: 'Solenoide de Cambio D Falla', description: 'El solenoide D de la transmisión no funciona.', symptoms: 'Transmisión en modo de emergencia', causes: 'Solenoide D defectuoso', solutions: '1. Reemplazar solenoide D.', severity: 'Moderada' },
  { code: 'P0770', title: 'Solenoide de Cambio E Falla', description: 'El solenoide E de la transmisión no funciona.', symptoms: 'Cambios anormales de transmisión', causes: 'Solenoide E defectuoso', solutions: '1. Reemplazar solenoide E.', severity: 'Moderada' },
  { code: 'P0800', title: 'Sistema de Control de Transferencia Falla', description: 'Problema en el sistema de transferencia de potencia (4WD/AWD).', symptoms: 'Sistema 4WD no funciona, Luz de 4WD encendida', causes: 'Módulo de transferencia defectuoso, Cableado suelto', solutions: '1. Escanear módulo de transferencia. 2. Reparar cableado.', severity: 'Moderada' },
  { code: 'P0811', title: 'Deslizamiento Excesivo del Embrague', description: 'El embrague está deslizando más de lo permitido.', symptoms: 'Aceleración sin aumento de velocidad, RPM suben pero no avanza', causes: 'Embrague desgastado, Fluido de transmisión bajo, Solenoide defectuoso', solutions: '1. Verificar fluido de transmisión. 2. Inspeccionar embrague.', severity: 'Crítica/No conducir' },
  // ── BODY (B) ────────────────────────────────────────────────────────────────
  { code: 'B0001', title: 'Falla en Circuito del Airbag del Conductor', description: 'Existe un problema en el circuito eléctrico del airbag frontal del conductor, lo que puede impedir su despliegue en un accidente.', symptoms: 'Luz de airbag SRS encendida permanentemente, El airbag podría no desplegarse en una colisión', causes: 'Módulo de airbag defectuoso, Cableado del volante dañado, Clockspring reloj espiral roto, Conector suelto', solutions: '1. NO intentar reparación casera. 2. Llevar a taller especializado en sistemas SRS. 3. Escanear con equipo profesional. 4. Reemplazar componente dañado.', severity: 'Crítica/No conducir' },
  { code: 'B0002', title: 'Falla en Circuito del Airbag del Pasajero', description: 'Problema en el circuito del airbag frontal del pasajero.', symptoms: 'Luz SRS encendida, Airbag pasajero podría no desplegarse', causes: 'Módulo defectuoso, Cableado dañado, Conector suelto', solutions: '1. Llevar a especialista en sistemas SRS.', severity: 'Crítica/No conducir' },
  { code: 'B0003', title: 'Falla en Circuito Airbag Lateral Conductor', description: 'Problema en el airbag lateral del lado del conductor.', symptoms: 'Luz SRS encendida, Airbag lateral no desplegaría en colisión', causes: 'Módulo lateral defectuoso, Cableado dañado', solutions: '1. Llevar a especialista en sistemas SRS.', severity: 'Crítica/No conducir' },
  { code: 'B0004', title: 'Falla en Circuito Airbag Lateral Pasajero', description: 'Problema en airbag lateral del lado pasajero.', symptoms: 'Luz SRS encendida, Airbag lateral pasajero no funcionaría', causes: 'Módulo defectuoso, Cableado suelto', solutions: '1. Llevar a especialista SRS.', severity: 'Crítica/No conducir' },
  { code: 'B0005', title: 'Falla en Circuito Cortina Airbag', description: 'Problema en la cortina de aire de techo del vehículo.', symptoms: 'Luz SRS encendida, Cortina de aire no desplegaría', causes: 'Módulo de cortina defectuoso, Inflador dañado', solutions: '1. Llevar a especialista SRS.', severity: 'Crítica/No conducir' },
  { code: 'B0006', title: 'Falla Pretensores Cinturón de Seguridad', description: 'Los pretensores del cinturón de seguridad no funcionan correctamente.', symptoms: 'Luz SRS encendida, Pretensores no activarían en impacto', causes: 'Módulo pretensor defectuoso, Cinturón previamente desplegado', solutions: '1. Llevar a especialista SRS. 2. Reemplazar cinturón si fue desplegado.', severity: 'Crítica/No conducir' },
  { code: 'B0010', title: 'Módulo de Control SRS Falla General', description: 'El módulo de control principal del sistema de airbags y restricción suplementaria falla.', symptoms: 'Múltiples luces de advertencia SRS, Sistema de airbags desactivado', causes: 'Módulo SRS defectuoso, Cortocircuito en sistema', solutions: '1. Llevar a especialista. 2. Reemplazar módulo SRS. 3. Verificar airbags usados.', severity: 'Crítica/No conducir' },
  { code: 'B0050', title: 'Sensor de Impacto Frontal Centro Falla', description: 'Falla del sensor de impacto frontal central, crítico para activación de airbags.', symptoms: 'Airbags no despliegarían en colisión frontal, Luz SRS', causes: 'Sensor dañado por colisión previa, Cableado roto', solutions: '1. Reemplazar sensor de impacto central.', severity: 'Crítica/No conducir' },
  { code: 'B0055', title: 'Sensor de Impacto Frontal Izquierdo Falla', description: 'Sensor de colisión frontal lado izquierdo defectuoso.', symptoms: 'Airbags lado izquierdo no despliegarían', causes: 'Sensor dañado, Cableado cortado', solutions: '1. Reparar cableado. 2. Reemplazar sensor.', severity: 'Crítica/No conducir' },
  { code: 'B0056', title: 'Sensor de Impacto Frontal Derecho Falla', description: 'Sensor de colisión frontal lado derecho defectuoso.', symptoms: 'Airbags lado derecho no despliegarían', causes: 'Sensor dañado físicamente', solutions: '1. Reemplazar sensor de impacto derecho.', severity: 'Crítica/No conducir' },
  { code: 'B0100', title: 'Falla del Sensor de Impacto Frontal Izquierdo', description: 'El sensor que detecta colisiones frontales del lado izquierdo no funciona correctamente.', symptoms: 'Luz de airbag encendida permanentemente, Sistema SRS desactivado', causes: 'Sensor de impacto dañado físicamente, Cableado cortado, Módulo de airbag defectuoso, Daño previo por colisión no reparado', solutions: '1. Inspeccionar sensor de impacto visualmente. 2. Verificar cableado hasta el módulo. 3. Llevar a técnico certificado en sistemas SRS.', severity: 'Crítica/No conducir' },
  { code: 'B0200', title: 'Falla General Sistema de Puertas Eléctricas', description: 'Problema general en el sistema de control de puertas eléctricas.', symptoms: 'Puertas no abren o cierran eléctricamente, Cerraduras anormales', causes: 'Módulo de puertas defectuoso, Actuadores rotos', solutions: '1. Revisar módulo de puertas. 2. Reemplazar actuadores dañados.', severity: 'Moderada' },
  { code: 'B0201', title: 'Puerta del Conductor Actuador Falla', description: 'El actuador de la puerta del conductor no funciona correctamente.', symptoms: 'Puerta conductor no abre o cierra con control remoto', causes: 'Actuador de puerta defectuoso, Conector suelto', solutions: '1. Reparar conexión. 2. Reemplazar actuador.', severity: 'Moderada' },
  { code: 'B0202', title: 'Puerta del Pasajero Actuador Falla', description: 'El actuador de la puerta del pasajero delantero tiene problemas.', symptoms: 'Puerta pasajero no responde a control eléctrico', causes: 'Actuador defectuoso', solutions: '1. Reemplazar actuador de puerta pasajero.', severity: 'Moderada' },
  { code: 'B0250', title: 'Sistema de Calefacción de Asientos Falla', description: 'El sistema de asientos calefactados no funciona.', symptoms: 'Asientos no calientan, Luz de asiento calefactado no enciende', causes: 'Elemento calefactor quemado, Conector suelto, Interruptor defectuoso', solutions: '1. Verificar interruptor. 2. Reparar conexión. 3. Reemplazar elemento calefactor.', severity: 'Baja' },
  { code: 'B0300', title: 'Falla Sistema de Iluminación Interior', description: 'Problema general en el sistema de iluminación de la cabina del vehículo.', symptoms: 'Luces interiores no encienden o no apagan, Iluminación anormal', causes: 'Módulo de iluminación defectuoso, Bombillas quemadas, Sensor de puerta falla', solutions: '1. Reemplazar bombillas. 2. Revisar módulo de iluminación. 3. Verificar sensor de puerta.', severity: 'Baja' },
  { code: 'B0400', title: 'Falla General Sistema de Espejos Eléctricos', description: 'Problema general en el sistema de espejos eléctricos.', symptoms: 'Espejos no se ajustan eléctricamente, Función de calefacción anormal', causes: 'Módulo de control defectuoso, Motores de espejo rotos', solutions: '1. Revisar módulo. 2. Reemplazar motor de espejo afectado.', severity: 'Moderada' },
  { code: 'B0450', title: 'Falla Motor Limpiaparabrisas', description: 'Problema general en el sistema de limpiaparabrisas.', symptoms: 'Limpiaparabrisas no funcionan o funcionan a velocidad única', causes: 'Motor de limpiaparabrisas quemado, Fusible quemado, Relay defectuoso', solutions: '1. Revisar fusible. 2. Verificar relay. 3. Reemplazar motor.', severity: 'Moderada' },
  { code: 'B0500', title: 'Sistema de Climatización A/C Falla General', description: 'Problema general en el sistema de aire acondicionado y calefacción del vehículo.', symptoms: 'A/C o calefacción no funciona o funciona incorrectamente', causes: 'Compresor de A/C defectuoso, Refrigerante bajo, Válvulas de expansión obstruidas', solutions: '1. Revisar presión del sistema. 2. Recargar refrigerante. 3. Verificar compresor.', severity: 'Moderada' },
  { code: 'B0550', title: 'Asiento Eléctrico del Conductor Falla', description: 'El asiento eléctrico del conductor no funciona correctamente.', symptoms: 'Asiento no se mueve en alguna dirección, Ajustes no funcionan', causes: 'Motor de asiento defectuoso, Conector suelto, Fusible quemado', solutions: '1. Verificar fusible. 2. Reparar conexión. 3. Reemplazar motor del asiento.', severity: 'Moderada' },
  // ── CHASSIS (C) ─────────────────────────────────────────────────────────────
  { code: 'C0035', title: 'Sensor ABS Rueda Trasera Izquierda Falla', description: 'El sensor ABS de la rueda trasera izquierda no envía señal correcta al módulo de frenos.', symptoms: 'Luz de ABS encendida, Frenos ABS no activan, Posible luz de tracción, Frenos convencionales funcionan', causes: 'Sensor ABS defectuoso, Rotor del sensor dañado o sucio, Cableado cortado, Gap incorrecto entre sensor y rotor', solutions: '1. Limpiar el sensor y el rotor con limpiador de frenos. 2. Verificar la distancia gap del sensor. 3. Revisar cableado. 4. Reemplazar sensor si es necesario.', severity: 'Moderada' },
  { code: 'C0036', title: 'Sensor ABS Rueda Trasera Derecha Falla', description: 'El sensor ABS de la rueda trasera derecha no funciona correctamente.', symptoms: 'Luz de ABS encendida, ABS inoperante lado trasero derecho', causes: 'Sensor defectuoso, Rotor de reluctancia dañado', solutions: '1. Limpiar sensor y rotor. 2. Reemplazar sensor si es necesario.', severity: 'Moderada' },
  { code: 'C0040', title: 'Sensor ABS Rueda Delantera Derecha Circuito Abierto', description: 'Circuito abierto en el sensor ABS de la rueda delantera derecha.', symptoms: 'Luz de ABS encendida, ABS desactivado', causes: 'Cable del sensor cortado, Conector suelto', solutions: '1. Reparar cable. 2. Verificar conector.', severity: 'Moderada' },
  { code: 'C0041', title: 'Sensor ABS Rueda Delantera Izquierda Falla', description: 'El sensor ABS de la rueda delantera izquierda no funciona correctamente.', symptoms: 'Luz de ABS encendida, ABS desactivado delantera izquierda', causes: 'Sensor defectuoso, Rotor de sensor dañado o contaminado', solutions: '1. Limpiar sensor y rotor. 2. Reemplazar sensor ABS.', severity: 'Moderada' },
  { code: 'C0042', title: 'Sensor ABS Rueda Delantera Derecha Falla', description: 'El sensor ABS de la rueda delantera derecha no funciona.', symptoms: 'Luz de ABS encendida, ABS desactivado', causes: 'Sensor ABS defectuoso', solutions: '1. Reemplazar sensor ABS delantera derecha.', severity: 'Moderada' },
  { code: 'C0050', title: 'Falla del Sensor de Velocidad de Rueda Delantera Derecha', description: 'El sensor ABS de la rueda delantera derecha reporta lecturas incorrectas o no envía señal.', symptoms: 'Luz de ABS encendida, Luz de control de tracción, Sistema ABS desactivado', causes: 'Sensor ABS frontal derecho dañado, Contaminación del sensor, Gap incorrecto, Cableado dañado', solutions: '1. Limpiar área del sensor y rotor. 2. Verificar gap entre sensor y rotor. 3. Inspeccionar cableado. 4. Reemplazar sensor si está dañado.', severity: 'Moderada' },
  { code: 'C0110', title: 'Motor de la Bomba ABS Falla', description: 'El motor de la bomba hidráulica del sistema ABS no funciona.', symptoms: 'Luz ABS encendida, Sistema ABS inoperante, Posible luz de estabilidad', causes: 'Motor de bomba ABS quemado, Fusible de bomba quemado', solutions: '1. Verificar fusible de la bomba ABS. 2. Reemplazar bomba/motor ABS.', severity: 'Moderada' },
  { code: 'C0121', title: 'Válvula Solenoide Freno Delantero Izquierdo Falla', description: 'La válvula solenoide que controla el freno delantero izquierdo en el sistema ABS no funciona.', symptoms: 'Luz ABS, Freno delantero izquierdo con comportamiento anormal', causes: 'Solenoide defectuoso, Cableado suelto', solutions: '1. Limpiar conexión. 2. Reemplazar solenoide.', severity: 'Moderada' },
  { code: 'C0200', title: 'Falla General Válvulas Solenoide ABS', description: 'Problema general en los solenoides del sistema ABS.', symptoms: 'Luz ABS, Frenado anormal en todas las ruedas', causes: 'Solenoide defectuoso, Cableado de solenoides suelto', solutions: '1. Reparar cableado. 2. Reemplazar solenoide afectado.', severity: 'Moderada' },
  { code: 'C0201', title: 'Circuito Solenoide Freno Delantero Izquierdo Falla', description: 'Problema en el solenoide del freno delantero izquierdo del sistema ABS.', symptoms: 'Luz ABS, Frenado desigual en delantera izquierda', causes: 'Solenoide defectuoso, Circuito abierto', solutions: '1. Reemplazar solenoide del freno delantero izquierdo.', severity: 'Moderada' },
  { code: 'C0202', title: 'Circuito Solenoide Freno Delantero Derecho Falla', description: 'Problema en el solenoide del freno delantero derecho del sistema ABS.', symptoms: 'Luz ABS, Frenado desigual en delantera derecha', causes: 'Solenoide defectuoso', solutions: '1. Reemplazar solenoide del freno delantero derecho.', severity: 'Moderada' },
  { code: 'C0203', title: 'Circuito Solenoide Freno Trasero Izquierdo Falla', description: 'Problema en el solenoide del freno trasero izquierdo del sistema ABS.', symptoms: 'Luz ABS, Frenado anormal trasero izquierdo', causes: 'Solenoide defectuoso', solutions: '1. Reemplazar solenoide del freno trasero izquierdo.', severity: 'Moderada' },
  { code: 'C0204', title: 'Circuito Solenoide Freno Trasero Derecho Falla', description: 'Problema en el solenoide del freno trasero derecho del sistema ABS.', symptoms: 'Luz ABS, Frenado anormal trasero derecho', causes: 'Solenoide defectuoso', solutions: '1. Reemplazar solenoide del freno trasero derecho.', severity: 'Moderada' },
  { code: 'C0265', title: 'Relé del Motor ABS Falla', description: 'El relé principal del motor de la bomba ABS tiene problemas.', symptoms: 'Luz ABS, Bomba ABS no arranca', causes: 'Relé quemado, Cableado defectuoso', solutions: '1. Reemplazar relé del motor ABS.', severity: 'Moderada' },
  { code: 'C0300', title: 'Módulo ABS/ESC Falla General', description: 'El módulo de control del sistema ABS y estabilidad electrónica tiene una falla general.', symptoms: 'Luz ABS, Luz de estabilidad, Frenos anormales', causes: 'Módulo ABS/ESC defectuoso, Problema de comunicación', solutions: '1. Escanear con equipo especializado. 2. Reemplazar módulo ABS.', severity: 'Moderada' },
  { code: 'C0550', title: 'Falla del Módulo ABS/Control de Tracción', description: 'El módulo de control que gestiona el ABS y el control de tracción tiene problemas.', symptoms: 'Luz ABS y TCS encendidas, Ambos sistemas desactivados', causes: 'Módulo defectuoso, Falla eléctrica interna', solutions: '1. Reemplazar módulo ABS/TCS.', severity: 'Moderada' },
  { code: 'C0710', title: 'Sensor de Ángulo de Dirección Falla', description: 'El sensor que mide el ángulo del volante no funciona correctamente.', symptoms: 'Luz de estabilidad encendida, Sistema de estabilidad desactivado', causes: 'Sensor de ángulo de dirección defectuoso, No calibrado después de alineación', solutions: '1. Calibrar sensor de ángulo de dirección. 2. Reemplazar sensor si es necesario.', severity: 'Moderada' },
  { code: 'C0800', title: 'Voltaje del Sistema ABS Bajo o Alto', description: 'Voltaje de alimentación del sistema ABS fuera de rango.', symptoms: 'Luz ABS intermitente, Sistema ABS errático', causes: 'Batería baja, Conexiones sueltas en módulo ABS', solutions: '1. Verificar batería. 2. Limpiar conexiones del módulo ABS.', severity: 'Moderada' },
  // ── NETWORK (U) ─────────────────────────────────────────────────────────────
  { code: 'U0001', title: 'Falla en Comunicación CAN Bus de Alto Nivel', description: 'Problema grave en la red de comunicación CAN de alta velocidad del vehículo.', symptoms: 'Múltiples luces de error simultáneas, Módulos no responden, Vehículo en modo de emergencia', causes: 'Bus CAN abierto o en cortocircuito, ECU defectuosa, Interferencia electromagnética', solutions: '1. Revisar cableado de bus CAN. 2. Verificar todas las ECUs con escáner. 3. Reparar o reemplazar ECU defectuosa.', severity: 'Crítica/No conducir' },
  { code: 'U0100', title: 'Pérdida de Comunicación con ECM/PCM Principal', description: 'Los módulos del vehículo no pueden comunicarse con la computadora principal del motor.', symptoms: 'Múltiples luces de advertencia, Vehículo no arranca, Varios sistemas no responden', causes: 'ECU principal defectuosa, Problemas en el bus de comunicación CAN, Fusible quemado, Cableado de red dañado', solutions: '1. Verificar fusibles relacionados con la ECU. 2. Revisar alimentación de la computadora. 3. Inspeccionar cableado del bus CAN. 4. Llevar a taller con equipo de diagnóstico avanzado.', severity: 'Crítica/No conducir' },
  { code: 'U0101', title: 'Pérdida de Comunicación con Módulo de Transmisión TCM', description: 'La computadora del motor no puede comunicarse con el módulo de control de la transmisión.', symptoms: 'Transmisión en modo de emergencia, Cambios erráticos, Luz de transmisión encendida', causes: 'Módulo TCM defectuoso, Problemas de comunicación CAN, Cableado dañado, Fusible quemado', solutions: '1. Verificar fusibles del TCM. 2. Inspeccionar conectores del módulo. 3. Diagnosticar bus CAN. 4. Probar módulo TCM.', severity: 'Crítica/No conducir' },
  { code: 'U0102', title: 'Pérdida de Comunicación con Módulo ABS', description: 'Problema de comunicación entre la ECU y el módulo ABS.', symptoms: 'Luz ABS encendida, Sistema de frenos ABS anormal', causes: 'Bus CAN abierto, Módulo ABS defectuoso', solutions: '1. Revisar cableado CAN. 2. Verificar módulo ABS.', severity: 'Moderada' },
  { code: 'U0103', title: 'Pérdida de Comunicación con Módulo Airbags SRS', description: 'El sistema de airbags no puede comunicarse con los demás módulos.', symptoms: 'Luz SRS encendida, Airbags no funcionarían correctamente', causes: 'Bus CAN abierto, Módulo SRS defectuoso', solutions: '1. Revisar cableado CAN. 2. Inspeccionar módulo SRS.', severity: 'Crítica/No conducir' },
  { code: 'U0121', title: 'Pérdida de Comunicación con Módulo de Control ABS', description: 'La red del vehículo perdió comunicación con el módulo de control del sistema ABS.', symptoms: 'Luz de ABS encendida, Posible pérdida de función ABS, Luz de estabilidad encendida', causes: 'Módulo ABS defectuoso, Problema en la red de comunicación CAN, Fusible quemado, Cableado dañado', solutions: '1. Verificar fusibles del sistema ABS. 2. Revisar alimentación del módulo. 3. Inspeccionar comunicación de red. 4. Probar módulo ABS con escáner.', severity: 'Moderada' },
  { code: 'U0122', title: 'Pérdida de Comunicación con Módulo de Estabilidad', description: 'El módulo de estabilidad electrónica ESP no puede comunicarse.', symptoms: 'Luz de estabilidad encendida, Sistema ESP desactivado', causes: 'Bus CAN abierto, Módulo de estabilidad defectuoso', solutions: '1. Revisar cableado CAN. 2. Verificar módulo ESP.', severity: 'Moderada' },
  { code: 'U0123', title: 'Pérdida de Comunicación con Módulo de Dirección', description: 'El módulo de dirección asistida eléctrica no puede comunicarse.', symptoms: 'Dirección pesada, Luz de dirección asistida', causes: 'Bus CAN abierto, Módulo de dirección defectuoso', solutions: '1. Revisar cableado CAN. 2. Verificar módulo de dirección.', severity: 'Crítica/No conducir' },
  { code: 'U0124', title: 'Pérdida de Comunicación con Módulo de Climatización', description: 'El módulo del sistema A/C y calefacción no puede comunicarse con la red.', symptoms: 'A/C o calefacción no funciona, Controles de clima no responden', causes: 'Bus CAN abierto, Módulo de climatización defectuoso', solutions: '1. Revisar cableado CAN. 2. Verificar módulo de climatización.', severity: 'Moderada' },
  { code: 'U0155', title: 'Pérdida de Comunicación con Módulo de Instrumentos', description: 'El tablero de instrumentos no puede comunicarse con la red CAN.', symptoms: 'Tablero apagado, Sin lecturas de velocidad o RPM', causes: 'Módulo de instrumentos defectuoso, Bus CAN abierto', solutions: '1. Revisar fusible del tablero. 2. Verificar cableado CAN. 3. Reemplazar módulo si es necesario.', severity: 'Moderada' },
  { code: 'U0164', title: 'Pérdida de Comunicación con Módulo HVAC', description: 'El módulo HVAC del climatizador no puede comunicarse.', symptoms: 'Sistema de climatización inoperante', causes: 'Módulo HVAC defectuoso, Bus CAN con problema', solutions: '1. Revisar cableado. 2. Reemplazar módulo HVAC.', severity: 'Moderada' },
  { code: 'U0168', title: 'Pérdida de Comunicación con Módulo de Control del Vehículo', description: 'El módulo central de control del vehículo no puede comunicarse.', symptoms: 'Múltiples sistemas sin respuesta', causes: 'Módulo VCM defectuoso, Bus CAN con error', solutions: '1. Diagnosticar bus CAN. 2. Reemplazar módulo VCM.', severity: 'Crítica/No conducir' },
  { code: 'U0200', title: 'Falla de Integridad de Datos en Bus CAN', description: 'Los datos transmitidos por el bus CAN contienen errores o son corruptos.', symptoms: 'Múltiples códigos erróneos, Funcionamiento errático de sistemas', causes: 'Interferencia electromagnética, Cableado CAN dañado, ECU defectuosa', solutions: '1. Revisar cableado CAN. 2. Buscar fuentes de interferencia. 3. Verificar todas las ECUs.', severity: 'Moderada' },
  { code: 'U1000', title: 'Código de Fabricante - Falla de Comunicación', description: 'Código de comunicación específico del fabricante. Indica problema en una red de comunicación propietaria.', symptoms: 'Varía según fabricante, Posibles luces de advertencia múltiples', causes: 'Módulo propietario defectuoso, Bus de comunicación del fabricante con problema', solutions: '1. Consultar documentación del fabricante. 2. Escanear con equipo específico de la marca.', severity: 'Moderada' },
  // ── ELÉCTRICOS (EV / Híbrido) ───────────────────────────────────────────────
  { code: 'P0A00', title: 'Falla General del Sistema de Batería de Alto Voltaje', description: 'El sistema de batería de alto voltaje (HV) del vehículo eléctrico o híbrido tiene un problema general.', symptoms: 'Luz de advertencia de batería EV, Reducción de potencia, Modo de seguridad activado, Carga limitada', causes: 'Módulo BMS defectuoso, Celdas de batería dañadas, Temperatura extrema, Problema de comunicación BMS', solutions: '1. Escanear sistema con equipo EV especializado. 2. Verificar temperatura de batería. 3. Revisar módulo BMS. 4. Llevar a concesionario autorizado EV.', severity: 'Crítica/No conducir' },
  { code: 'P0A01', title: 'Voltaje de Batería HV Demasiado Bajo', description: 'El voltaje del paquete de batería de alto voltaje está por debajo del rango mínimo operativo.', symptoms: 'Pérdida de potencia severa, Carga no disponible, Modo de emergencia activado', causes: 'Batería profundamente descargada, Celda defectuosa, Problema en sistema de carga', solutions: '1. Cargar batería inmediatamente. 2. Verificar sistema de carga. 3. Diagnosticar celdas individuales.', severity: 'Crítica/No conducir' },
  { code: 'P0A02', title: 'Voltaje de Batería HV Demasiado Alto', description: 'El voltaje del paquete de batería excede el límite máximo seguro de operación.', symptoms: 'Carga detenida automáticamente, Luz de advertencia, Modo de protección activo', causes: 'Sistema de carga defectuoso, BMS no regula correctamente, Problema en convertidor DC/DC', solutions: '1. Detener carga inmediatamente. 2. Revisar sistema de carga. 3. Verificar BMS.', severity: 'Crítica/No conducir' },
  { code: 'P0A03', title: 'Temperatura Alta de Batería de Alto Voltaje', description: 'La temperatura de la batería de alto voltaje excede el límite seguro de operación.', symptoms: 'Potencia reducida, Carga lenta o detenida, Advertencia de temperatura en tablero', causes: 'Sistema de enfriamiento de batería defectuoso, Uso intensivo, Temperatura ambiente muy alta', solutions: '1. Detener el vehículo y dejarlo enfriar. 2. Verificar sistema de enfriamiento de batería. 3. Revisar bomba de refrigerante.', severity: 'Crítica/No conducir' },
  { code: 'P0A04', title: 'Temperatura Baja de Batería HV', description: 'La temperatura de la batería está demasiado baja para operación normal.', symptoms: 'Rango de conducción reducido, Carga lenta, Potencia limitada en frío', causes: 'Temperatura ambiente muy baja, Sistema de calefacción de batería defectuoso', solutions: '1. Precalentar el vehículo. 2. Verificar sistema de calefacción de batería. 3. Estacionar en área cubierta.', severity: 'Moderada' },
  { code: 'P0A05', title: 'Celda de Batería HV Débil Detectada', description: 'Una o más celdas del paquete de batería de alto voltaje tienen capacidad reducida.', symptoms: 'Rango reducido de conducción, Carga irregular, Degradación de batería evidente', causes: 'Envejecimiento natural de celdas, Ciclos de carga profunda repetidos, Temperatura extrema acumulada', solutions: '1. Diagnóstico completo de celdas con equipo especializado. 2. Evaluar reemplazo de módulo de batería afectado.', severity: 'Moderada' },
  { code: 'P0A06', title: 'Desbalance de Celdas en Batería HV', description: 'Las celdas del paquete de batería tienen voltajes muy diferentes entre sí.', symptoms: 'Rango reducido, Comportamiento irregular en carga, Batería se descarga más rápido', causes: 'Envejecimiento diferencial de celdas, Problema en balanceador BMS, Celda defectuosa', solutions: '1. Diagnóstico del BMS. 2. Balanceo de celdas por técnico especializado. 3. Posible reemplazo de módulo.', severity: 'Moderada' },
  { code: 'P0A08', title: 'Falla en Sistema de Aislamiento de Batería HV', description: 'Se detectó una fuga de corriente entre el sistema de alto voltaje y la carrocería del vehículo.', symptoms: 'Luz de falla de aislamiento, Posible choque eléctrico, Sistema de seguridad activo', causes: 'Daño en aislamiento de cables HV, Humedad en conector HV, Corto a tierra en sistema eléctrico HV', solutions: '1. NO tocar cables de alto voltaje sin protección. 2. Llevar inmediatamente a taller autorizado EV.', severity: 'Crítica/No conducir' },
  { code: 'P0A09', title: 'Falla en Relé Principal de Batería HV', description: 'El relé principal que conecta y desconecta la batería del sistema eléctrico no funciona.', symptoms: 'Vehículo no arranca, Sin potencia eléctrica, Sistema inoperante', causes: 'Relé principal dañado, Solenoide quemado, Problema eléctrico en circuito de control', solutions: '1. NO intentar reparación sin equipo especializado EV. 2. Llevar a taller autorizado.', severity: 'Crítica/No conducir' },
  { code: 'P0A0F', title: 'Fin de Vida Estimado de la Batería HV', description: 'El sistema BMS detecta que la batería ha llegado al final de su vida útil estimada.', symptoms: 'Rango drásticamente reducido, Advertencia de degradación severa, Carga muy lenta', causes: 'Envejecimiento natural acumulado, Ciclos de carga excesivos, Uso en condiciones extremas', solutions: '1. Evaluar reemplazo del paquete de batería. 2. Consultar garantía del fabricante. 3. Diagnóstico completo por especialista EV.', severity: 'Moderada' },
  { code: 'P0A19', title: 'Sensor de Temperatura de Batería HV Falla', description: 'El sensor que mide la temperatura de la batería de alto voltaje no funciona correctamente.', symptoms: 'Carga limitada como precaución, Potencia reducida, Advertencia de batería en tablero', causes: 'Sensor de temperatura defectuoso, Cableado dañado, Conector suelto en BMS', solutions: '1. Verificar conexiones del sensor de temperatura. 2. Reemplazar sensor de temperatura de batería.', severity: 'Moderada' },
  { code: 'P0A1F', title: 'Falla en Sistema de Monitoreo de Batería BMS', description: 'El sistema de gestión de batería (BMS) tiene un fallo general que compromete la seguridad.', symptoms: 'Múltiples advertencias de batería, Carga no disponible, Estimaciones de autonomía incorrectas', causes: 'Módulo BMS defectuoso, Error de software, Problema de comunicación interna', solutions: '1. Actualizar software del BMS. 2. Reemplazar módulo BMS si persiste.', severity: 'Crítica/No conducir' },
  { code: 'P0A3F', title: 'Calefactor de Batería HV Falla', description: 'El sistema que precalienta la batería en climas fríos no funciona correctamente.', symptoms: 'Rango reducido en climas fríos, Carga lenta en temperaturas bajas', causes: 'Elemento calefactor defectuoso, Circuito abierto, Bomba de calefacción falla', solutions: '1. Verificar circuito del calefactor. 2. Reemplazar elemento calefactor de batería.', severity: 'Moderada' },
  { code: 'P0A7A', title: 'Sistema de Enfriamiento de Batería HV Falla', description: 'El sistema de refrigeración líquida de la batería de alto voltaje no funciona correctamente.', symptoms: 'Temperatura de batería alta, Potencia reducida, Advertencia de temperatura', causes: 'Bomba de refrigerante defectuosa, Fuga de refrigerante, Radiador de batería obstruido', solutions: '1. Verificar nivel de refrigerante. 2. Inspeccionar bomba de refrigeración. 3. Revisar radiador de batería.', severity: 'Crítica/No conducir' },
  { code: 'P0A80', title: 'Reemplazar Módulo de Batería HV', description: 'El sistema detecta que uno o más módulos del paquete de batería deben reemplazarse.', symptoms: 'Rango reducido significativamente, Advertencia de degradación severa', causes: 'Módulo de batería muy degradado, Celda con falla interna', solutions: '1. Diagnóstico completo de módulos individuales. 2. Reemplazar módulo afectado. 3. Consultar garantía del fabricante.', severity: 'Moderada' },
  { code: 'P0A94', title: 'Convertidor DC/DC Falla', description: 'El convertidor que transforma el voltaje HV de la batería al voltaje de 12V del sistema auxiliar no funciona.', symptoms: 'Batería 12V no se carga, Luces tenues, Sistema auxiliar falla progresivamente', causes: 'Convertidor DC/DC defectuoso, Problema eléctrico en circuito de conversión', solutions: '1. Revisar voltaje de salida del convertidor. 2. Reemplazar convertidor DC/DC.', severity: 'Crítica/No conducir' },
  { code: 'P0B00', title: 'Falla General del Motor Eléctrico de Propulsión', description: 'El motor eléctrico principal de propulsión tiene un fallo general.', symptoms: 'Sin propulsión eléctrica, Pérdida total de potencia, Modo de emergencia activo', causes: 'Motor eléctrico defectuoso, Inversor dañado, Problema de comunicación del motor', solutions: '1. Llevar inmediatamente a taller autorizado EV.', severity: 'Crítica/No conducir' },
  { code: 'P0B01', title: 'Temperatura Alta del Motor Eléctrico', description: 'La temperatura del motor eléctrico de propulsión excede el límite seguro.', symptoms: 'Potencia reducida, Advertencia de temperatura, Modo de protección activo', causes: 'Sistema de enfriamiento del motor defectuoso, Uso intensivo prolongado, Temperatura ambiente extrema', solutions: '1. Reducir velocidad y carga. 2. Verificar sistema de enfriamiento del motor. 3. Dejar enfriar antes de continuar.', severity: 'Crítica/No conducir' },
  { code: 'P0B15', title: 'Falla del Inversor del Motor Eléctrico', description: 'El inversor que convierte la corriente DC de la batería a corriente AC para el motor no funciona.', symptoms: 'Sin propulsión o propulsión muy reducida, Motor eléctrico no responde', causes: 'Inversor defectuoso, IGBT quemado, Sobrecalentamiento del inversor', solutions: '1. Diagnóstico del inversor con equipo especializado EV. 2. Reemplazar inversor si es necesario.', severity: 'Crítica/No conducir' },
  { code: 'P0B1A', title: 'Sensor de Posición del Rotor Motor Eléctrico Falla', description: 'El sensor encoder que mide la posición del rotor del motor eléctrico no funciona.', symptoms: 'Propulsión errática, Ruido anormal del motor eléctrico, Vibraciones inusuales', causes: 'Sensor de posición del rotor defectuoso, Encoder dañado', solutions: '1. Reemplazar sensor de posición del rotor.', severity: 'Crítica/No conducir' },
  { code: 'P0B25', title: 'Temperatura Alta del Inversor del Motor', description: 'La temperatura del inversor del motor eléctrico es demasiado alta.', symptoms: 'Potencia reducida como protección, Advertencia de temperatura del inversor', causes: 'Sistema de enfriamiento del inversor defectuoso, Uso intensivo de propulsión', solutions: '1. Verificar sistema de enfriamiento del inversor. 2. Reducir carga de propulsión.', severity: 'Crítica/No conducir' },
  { code: 'P0C00', title: 'Falla General del Sistema de Transmisión Eléctrica', description: 'El sistema de transmisión del vehículo eléctrico tiene un fallo general.', symptoms: 'Propulsión anormal, Ruido de transmisión eléctrica, Cambios bruscos', causes: 'Módulo de transmisión eléctrica defectuoso, Problema mecánico en reducción', solutions: '1. Diagnóstico completo con equipo EV especializado.', severity: 'Crítica/No conducir' },
  { code: 'P0C20', title: 'Falla en Sistema de Frenado Regenerativo', description: 'El sistema de frenado regenerativo que recupera energía al frenar no funciona correctamente.', symptoms: 'Sin recuperación de energía al frenar, Pedal de freno con sensación diferente, Menor eficiencia energética', causes: 'Inversor defectuoso, BMS no acepta carga regenerativa, Batería completamente llena', solutions: '1. Verificar estado de carga de batería. 2. Diagnosticar inversor. 3. Revisar BMS.', severity: 'Moderada' },
  { code: 'P0C25', title: 'Coordinación Frenado Regenerativo-Mecánico Falla', description: 'La coordinación entre el frenado regenerativo y los frenos mecánicos tiene un error de calibración.', symptoms: 'Frenado irregular, Pedal de freno con respuesta inconsistente', causes: 'Módulo de control de frenos defectuoso, Calibración incorrecta del sistema de freno combinado', solutions: '1. Recalibrar sistema de frenos combinado. 2. Actualizar software del módulo de frenos.', severity: 'Crítica/No conducir' },
  { code: 'P0D00', title: 'Falla General del Sistema de Carga EV', description: 'El sistema de carga del vehículo eléctrico tiene un fallo general.', symptoms: 'No acepta carga, Carga muy lenta, Error en cargador', causes: 'Cargador onboard OBC defectuoso, Problema en conector de carga, BMS no acepta carga', solutions: '1. Verificar conector de carga. 2. Intentar otro cargador. 3. Diagnóstico del OBC.', severity: 'Crítica/No conducir' },
  { code: 'P0D0A', title: 'Falla en Cargador Onboard AC (Nivel 1/2)', description: 'El cargador interno del vehículo para carga AC de nivel 1 o nivel 2 no funciona.', symptoms: 'No carga con cable AC, Error al conectar cargador doméstico o de pared', causes: 'OBC defectuoso, Fusible de carga quemado, Cableado interno dañado', solutions: '1. Verificar fusible del OBC. 2. Revisar cableado de conexión. 3. Reemplazar OBC.', severity: 'Crítica/No conducir' },
  { code: 'P0D0B', title: 'Falla en Carga Rápida DC (CHAdeMO/CCS)', description: 'El sistema de carga rápida en corriente directa no funciona correctamente.', symptoms: 'No acepta carga rápida DC, Error en estación de carga rápida', causes: 'Puerto de carga DC dañado, Convertidor de carga rápida defectuoso, BMS rechaza carga rápida', solutions: '1. Limpiar conector DC. 2. Verificar convertidor de carga rápida. 3. Diagnóstico del sistema con equipo EV.', severity: 'Crítica/No conducir' },
  { code: 'P0D10', title: 'Falla en Comunicación con Cargador Externo', description: 'El vehículo no puede establecer comunicación con el cargador externo conectado.', symptoms: 'Carga no inicia, Error de comunicación con cargador', causes: 'Protocolo de comunicación incompatible, Cableado de señal dañado, Cargador externo defectuoso', solutions: '1. Intentar otro cable de carga. 2. Probar en otra estación de carga. 3. Verificar compatibilidad del protocolo.', severity: 'Moderada' },
  { code: 'P0D15', title: 'Temperatura Alta del Cargador Onboard OBC', description: 'El cargador interno del vehículo está sobrecalentado durante la carga.', symptoms: 'Carga detenida automáticamente, Advertencia de temperatura del cargador', causes: 'Carga continua muy prolongada, Temperatura ambiente alta, Ventilación del cargador bloqueada', solutions: '1. Detener carga y dejar enfriar. 2. Verificar ventilación del área del cargador. 3. Reanudar cuando enfríe.', severity: 'Moderada' },
  { code: 'P0D20', title: 'Límite de Corriente de Carga Excedido', description: 'La corriente durante la carga supera el límite máximo permitido por el sistema.', symptoms: 'Carga detenida por protección de seguridad, Advertencia de corriente excesiva', causes: 'Cargador externo defectuoso, BMS no regula correctamente la carga', solutions: '1. Usar otro cargador externo. 2. Verificar configuración del BMS.', severity: 'Crítica/No conducir' },
  { code: 'P0D25', title: 'Puerto de Carga Dañado o Contaminado', description: 'El puerto de carga del vehículo tiene daño físico o contaminación que impide la carga.', symptoms: 'No conecta el cable cargador correctamente, Error físico visible en el puerto', causes: 'Daño físico por objeto extraño, Corrosión en pines, Humedad acumulada en el puerto', solutions: '1. Limpiar puerto de carga con aire comprimido. 2. Inspeccionar daños físicos. 3. Reemplazar puerto si está dañado.', severity: 'Moderada' },
  { code: 'P0D30', title: 'Falla en Precondicionamiento de Batería para Carga Rápida', description: 'El sistema que lleva la batería a temperatura óptima antes de la carga rápida no funciona.', symptoms: 'Carga rápida más lenta de lo normal, Batería no alcanza temperatura óptima para carga rápida', causes: 'Sistema de calefacción de batería defectuoso, Software de precondicionamiento con error', solutions: '1. Verificar sistema de calefacción de batería. 2. Actualizar software del sistema de carga.', severity: 'Moderada' },
  { code: 'P0A1E', title: 'Módulo de Control de Energía Híbrido HCM Falla', description: 'El módulo que coordina el uso del motor de combustión y el motor eléctrico en un híbrido tiene problemas.', symptoms: 'Transición brusca entre modos de propulsión, Luz de advertencia del sistema híbrido', causes: 'Módulo HCM defectuoso, Problema de calibración, Error de software híbrido', solutions: '1. Actualizar software del HCM. 2. Reemplazar módulo si persiste.', severity: 'Crítica/No conducir' },
  { code: 'P0A26', title: 'Motor Generador en Modo Carga Falla', description: 'El motor generador no puede cargar la batería HV mientras el motor de combustión está en marcha.', symptoms: 'Batería híbrida no se carga durante la conducción, Indicador de batería baja', causes: 'Motor generador defectuoso, Inversor del generador dañado', solutions: '1. Diagnóstico del motor generador. 2. Revisar inversor del generador.', severity: 'Crítica/No conducir' },
  { code: 'P0A3E', title: 'Arranque del Motor de Combustión por Motor Eléctrico Falla', description: 'El motor eléctrico no puede arrancar el motor de combustión en el sistema híbrido.', symptoms: 'Motor de combustión no arranca en modo híbrido, Solo modo eléctrico disponible con batería', causes: 'Motor generador arrancador defectuoso, Batería híbrida muy baja, Conexión eléctrica falla', solutions: '1. Verificar nivel de batería HV. 2. Revisar conexiones eléctricas. 3. Diagnóstico del motor generador.', severity: 'Crítica/No conducir' },
];

async function main() {
  console.log('Iniciando seed Fase 2 - Estructura Relacional...');

  // 1. Limpiar tablas en orden correcto (FK constraints)
  await prisma.codeVehicleCompatibility.deleteMany();
  await prisma.oBDCodeTranslation.deleteMany();
  await prisma.oBDSolution.deleteMany();
  await prisma.oBDCause.deleteMany();
  await prisma.oBDSymptom.deleteMany();
  await prisma.oBDCode.deleteMany();
  await prisma.vehicleType.deleteMany();
  await prisma.oBDCategory.deleteMany();
  await prisma.manufacturer.deleteMany();
  console.log('Tablas limpiadas.');

  // 1b. Fabricantes: centinela genérico (SAE) + marcas principales de
  //     LatAm/US/Canadá listas para recibir códigos OEM en la Fase 3.
  console.log('Creando fabricantes...');
  let genericManufacturerId = 0;
  for (const m of MANUFACTURERS) {
    const created = await prisma.manufacturer.create({ data: m });
    if (m.isGeneric) genericManufacturerId = created.id;
  }
  console.log(`  ${MANUFACTURERS.length} fabricantes creados (genérico id=${genericManufacturerId}).`);

  // 2. Crear categorías
  console.log('Creando categorias...');
  const catMap: Record<string, number> = {};
  for (const cat of CATEGORIES) {
    const created = await prisma.oBDCategory.create({ data: cat });
    catMap[cat.code] = created.id;
  }
  console.log(`  ${CATEGORIES.length} categorias creadas.`);

  // 3. Crear tipos de vehículo
  console.log('Creando tipos de vehiculo...');
  const vtMap: Record<string, number> = {};
  for (const vt of VEHICLE_TYPES) {
    const created = await prisma.vehicleType.create({ data: vt });
    vtMap[vt.type] = created.id;
  }
  console.log(`  ${VEHICLE_TYPES.length} tipos de vehiculo creados.`);

  // 4. Combinar códigos curados (incluye EV) + códigos nuevos del CSV
  const existingCodes = new Set(ALL_CODES.map((c) => c.code.toUpperCase()));
  const CSV_PATH = path.resolve(__dirname, '..', '..', 'OBD2_CODES_500.csv');
  const csvCodes = loadCsvCodes(CSV_PATH, existingCodes);
  const MERGED = [...ALL_CODES, ...csvCodes];
  console.log(`  Curados: ${ALL_CODES.length} · Nuevos del CSV: ${csvCodes.length} · Total: ${MERGED.length}`);

  // 5. Crear códigos con relaciones
  console.log(`Insertando ${MERGED.length} codigos OBD2...`);
  let inserted = 0;

  for (const codeData of MERGED) {
    const categoryLetter = codeData.code[0].toUpperCase();
    const categoryId = catMap[categoryLetter];
    if (!categoryId) {
      console.log(`  SKIP: Categoria no encontrada para ${codeData.code}`);
      continue;
    }

    const created = await prisma.oBDCode.create({
      data: {
        code: codeData.code,
        title: codeData.title,
        description: codeData.description,
        severity: codeData.severity,
        categoryId,
        manufacturerId: genericManufacturerId,
        status: 'PUBLISHED',
        source: 'seed',
      },
    });

    for (const symptom of splitList(codeData.symptoms)) {
      await prisma.oBDSymptom.create({ data: { codeId: created.id, symptom } });
    }
    for (const cause of splitList(codeData.causes)) {
      await prisma.oBDCause.create({ data: { codeId: created.id, cause } });
    }
    for (const solution of splitList(codeData.solutions)) {
      await prisma.oBDSolution.create({ data: { codeId: created.id, solution } });
    }
    for (const vType of getVehicleCompat(codeData.code)) {
      const vehicleTypeId = vtMap[vType];
      if (vehicleTypeId) {
        await prisma.codeVehicleCompatibility.create({
          data: { codeId: created.id, vehicleTypeId, applicable: true },
        });
      }
    }

    inserted++;
    if (inserted % 20 === 0 || inserted === MERGED.length) {
      console.log(`  [${inserted}/${MERGED.length}] Insertados...`);
    }
  }

  const total = await prisma.oBDCode.count();
  console.log(`\n${total} codigos insertados.`);

  // 6. Traducciones al inglés (primer lote de códigos de alto tráfico)
  console.log('Cargando traducciones EN...');
  const tr = await loadEnglishTranslations(prisma);
  console.log(`  ${tr.loaded} traducciones EN cargadas${tr.missing.length ? ` (omitidos: ${tr.missing.join(', ')})` : ''}.`);

  // 7. Códigos OEM por fabricante (Fase 3), con su contenido ES + EN
  console.log('Cargando códigos OEM por fabricante...');
  const oem = await loadOemCodes(prisma);
  console.log(`  ${oem.loaded} códigos OEM cargados${oem.skipped.length ? ` (omitidos: ${oem.skipped.join(', ')})` : ''}.`);

  console.log('\nSeed completado.');
}

main()
  .catch((e) => {
    console.error('Error en seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
