/* Lote 5 de traducciones EN: P05 (sensor de velocidad VSS, control de ralentí,
   presión de aceite, presión A/C, calefactor de admisión, presión de
   combustible, voltaje del sistema eléctrico). */

import type { CodeTranslation } from './translations-en';

export const EN_TRANSLATIONS_5: CodeTranslation[] = [
  { code: 'P0501', title: 'Vehicle Speed Sensor (VSS) Range/Performance', description: 'The speed sensor sends an out-of-range signal.', symptoms: ['Incorrect speedometer', 'Irregular transmission shifting'], causes: ['Miscalibrated VSS sensor', 'Magnetic interference'], solutions: ['Replace the VSS sensor'] },
  { code: 'P0502', title: 'VSS Circuit Low Input', description: 'Low voltage at the speed sensor.', symptoms: ['Speedometer reads very low or not at all'], causes: ['Sensor with low resistance'], solutions: ['Replace the sensor'] },
  { code: 'P0503', title: 'VSS Circuit Intermittent/Erratic', description: 'Unstable voltage at the speed sensor.', symptoms: ['Fluctuating speedometer', 'Erratic shifting'], causes: ['Intermittent connection', 'Faulty sensor'], solutions: ['Clean the connectors', 'Replace the sensor'] },
  { code: 'P0504', title: 'Brake Switch Correlation', description: 'The brake sensors report inconsistent data.', symptoms: ['Abnormal brake light', 'Erratic ABS behavior'], causes: ['Faulty brake switch', 'Damaged wiring'], solutions: ['Check the brake switches', 'Repair the wiring'] },
  { code: 'P0506', title: 'Idle Control System RPM Lower Than Expected', description: 'The engine idles lower than the programmed range.', symptoms: ['Very low idle', 'Engine nearly stalls', 'Heavy vibration'], causes: ['Air leak', 'Dirty MAF sensor', 'Faulty controller'], solutions: ['Look for air leaks', 'Clean the MAF sensor'] },
  { code: 'P0507', title: 'Idle Control System RPM Higher Than Expected', description: 'The engine idles higher than normal.', symptoms: ['Very high idle', 'Excessive consumption while driving'], causes: ['Air leak after the MAF sensor', 'Stuck thermostat', 'IAC stuck open'], solutions: ['Look for air leaks', 'Check the thermostat', 'Clean the IAC'] },
  { code: 'P0508', title: 'Idle Control Circuit Low', description: 'Low voltage in the idle control circuit.', symptoms: ['Low idle or engine nearly stalls'], causes: ['Open circuit', 'High resistance'], solutions: ['Repair the control circuit'] },
  { code: 'P0509', title: 'Idle Control Circuit High', description: 'High voltage in the idle control circuit.', symptoms: ['Very high idle'], causes: ['Short circuit'], solutions: ['Repair the circuit'] },
  { code: 'P0510', title: 'Closed Throttle Position Out of Range', description: 'The throttle position voltage is out of range.', symptoms: ['Erratic engine', 'Acceleration problems'], causes: ['Faulty TPS sensor', 'Loose connections'], solutions: ['Recalibrate or replace the TPS'] },
  { code: 'P0521', title: 'Engine Oil Pressure Sensor Range/Performance', description: 'The oil pressure sensor sends an out-of-range signal.', symptoms: ['Erratic pressure reading', 'Intermittent oil light'], causes: ['Miscalibrated sensor', 'Actual low oil level'], solutions: ['Check the oil level', 'Replace the sensor'] },
  { code: 'P0522', title: 'Engine Oil Pressure Sensor Low Voltage', description: 'Low voltage at the pressure sensor.', symptoms: ['Gauge reads zero'], causes: ['Sensor with low resistance'], solutions: ['Replace the sensor'] },
  { code: 'P0523', title: 'Engine Oil Pressure Sensor High Voltage', description: 'High voltage at the pressure sensor.', symptoms: ['Gauge reads very high'], causes: ['Sensor with high resistance'], solutions: ['Replace the sensor'] },
  { code: 'P0530', severity: 'Baja', title: 'A/C Pressure Sensor Circuit Malfunction', description: 'The sensor that measures A/C pressure does not work.', symptoms: ['A/C does not cool', 'Compressor does not engage'], causes: ['Faulty sensor', 'Loose connector', 'Abnormal system pressure'], solutions: ['Replace the sensor', 'Check the A/C pressure'] },
  { code: 'P0531', severity: 'Baja', title: 'A/C Pressure Sensor Range/Performance', description: 'A/C pressure sensor out of range.', symptoms: ['Abnormal A/C'], causes: ['Faulty sensor'], solutions: ['Replace the sensor'] },
  { code: 'P0532', severity: 'Baja', title: 'A/C Pressure Sensor Low Input', description: 'Low voltage at the A/C sensor.', symptoms: ['A/C does not work'], causes: ['Sensor with low resistance'], solutions: ['Replace the sensor'] },
  { code: 'P0533', severity: 'Baja', title: 'A/C Pressure Sensor High Input', description: 'High voltage at the A/C sensor.', symptoms: ['Abnormal A/C'], causes: ['Sensor with high resistance'], solutions: ['Replace the sensor'] },
  { code: 'P0534', severity: 'Baja', title: 'A/C Refrigerant Charge Loss', description: 'Low refrigerant level in the A/C system.', symptoms: ['A/C does not cool', 'Pressure light'], causes: ['Refrigerant leak in the A/C system'], solutions: ['Look for leaks', 'Recharge the refrigerant'] },
  { code: 'P0540', severity: 'Baja', title: 'Intake Air Heater Control Circuit', description: 'Problem in the intake air heater circuit.', symptoms: ['Intake air does not warm up', 'Low idle'], causes: ['Faulty heating element', 'Loose connector'], solutions: ['Repair the connection', 'Replace the element'] },
  { code: 'P0541', severity: 'Baja', title: 'Intake Air Heater Circuit Low', description: 'Low voltage at the intake heater.', symptoms: ['Air does not warm up'], causes: ['Open circuit'], solutions: ['Repair the circuit'] },
  { code: 'P0542', severity: 'Baja', title: 'Intake Air Heater Circuit High', description: 'High voltage at the intake heater.', symptoms: ['Overheating'], causes: ['Overheating', 'Short circuit'], solutions: ['Repair the circuit'] },
  { code: 'P0550', title: 'Power Steering Pressure Sensor Circuit', description: 'The power steering/fuel pressure sensor does not work.', symptoms: ['Hard starting', 'Power loss', 'Check Engine light'], causes: ['Faulty sensor', 'Loose connector', 'Low pressure'], solutions: ['Check the pressure', 'Replace the sensor'] },
  { code: 'P0551', title: 'Power Steering Pressure Sensor Range/Performance', description: 'Pressure sensor out of range.', symptoms: ['Abnormal operation'], causes: ['Faulty sensor'], solutions: ['Replace the sensor'] },
  { code: 'P0552', title: 'Power Steering Pressure Sensor Low Input', description: 'Low voltage at the pressure sensor.', symptoms: ['Hard starting'], causes: ['Sensor with low resistance'], solutions: ['Replace the sensor'] },
  { code: 'P0553', title: 'Power Steering Pressure Sensor High Input', description: 'High voltage at the pressure sensor.', symptoms: ['Abnormal starting'], causes: ['Sensor with high resistance'], solutions: ['Replace the sensor'] },
  { code: 'P0554', title: 'Power Steering Pressure Sensor Intermittent', description: 'Intermittent sensor readings.', symptoms: ['Erratic starting'], causes: ['Intermittent connection'], solutions: ['Clean the connectors'] },
  { code: 'P0560', title: 'System Voltage Malfunction', description: 'A general problem was detected in the vehicle electrical system voltage.', symptoms: ['Battery light on', 'Weak cranking', 'Accessories with low voltage'], causes: ['Low battery', 'Faulty alternator', 'Corroded connections'], solutions: ['Check the battery', 'Test the alternator'] },
  { code: 'P0561', title: 'System Voltage Unstable', description: 'Unstable voltage in the system.', symptoms: ['Lights flicker erratically'], causes: ['Weak charging', 'Intermittent alternator', 'Battery with dead cells'], solutions: ['Test the alternator', 'Replace the battery'] },
  { code: 'P0563', title: 'System Voltage High', description: 'Electrical system voltage above 16V.', symptoms: ['Electronic component burnout', 'Very bright lights'], causes: ['Faulty alternator voltage regulator'], solutions: ['Replace the regulator', 'Check the alternator'] },
  { code: 'P0564', title: 'Cruise Control Multi-Function Input Signal', description: 'Problem in the cruise control / auxiliary input signal.', symptoms: ['Erratic cruise behavior'], causes: ['Faulty sensor'], solutions: ['Replace the sensor'] },
];
