/* Lote 9 de traducciones EN: U (red de comunicación / bus CAN: pérdida de
   comunicación con módulos, voltaje del bus, integridad de datos, timeouts,
   código de fabricante). Completa la cobertura del catálogo. */

import type { CodeTranslation } from './translations-en';

export const EN_TRANSLATIONS_9: CodeTranslation[] = [
  { code: 'U0001', severity: 'Crítica/No conducir', title: 'High Speed CAN Communication Bus Malfunction', description: 'Serious problem in the vehicle high-speed CAN communication network.', symptoms: ['Multiple simultaneous error lights', 'Modules not responding', 'Vehicle in limp mode'], causes: ['CAN bus open or short-circuited', 'Faulty ECU', 'Electromagnetic interference'], solutions: ['Check the CAN bus wiring', 'Check all ECUs with a scan tool', 'Repair or replace the faulty ECU'] },
  { code: 'U0010', title: 'Lost Communication with Information Display', description: 'The display module does not respond to commands.', symptoms: ['Display does not show information', 'No response'], causes: ['Open CAN bus', 'Faulty display module'], solutions: ['Check the wiring', 'Replace the display module'] },
  { code: 'U0011', title: 'Lost Communication with Door Module', description: 'The door control module does not communicate.', symptoms: ['Doors do not respond', 'Abnormal locks'], causes: ['Open CAN bus', 'Faulty door module'], solutions: ['Check the CAN wiring'] },
  { code: 'U0020', title: 'Low Speed CAN Communication Bus Low', description: 'Low voltage on the CAN bus.', symptoms: ['Multiple codes', 'Poor communication'], causes: ['Short circuit', 'Low power source'], solutions: ['Check the source voltage'] },
  { code: 'U0021', title: 'Low Speed CAN Communication Bus High', description: 'High voltage on the CAN bus.', symptoms: ['Data corruption', 'Multiple codes'], causes: ['Bus overload', 'Short circuit'], solutions: ['Check the voltage'] },
  { code: 'U0100', severity: 'Crítica/No conducir', title: 'Lost Communication with ECM/PCM', description: 'The vehicle modules cannot communicate with the main engine computer.', symptoms: ['Multiple warning lights', 'Vehicle does not start', 'Several systems not responding'], causes: ['Faulty main ECU', 'CAN communication bus problems', 'Blown fuse', 'Damaged network wiring'], solutions: ['Check ECU-related fuses', 'Check the computer power supply', 'Inspect the CAN bus wiring', 'Take it to a shop with advanced diagnostic equipment'] },
  { code: 'U0101', severity: 'Crítica/No conducir', title: 'Lost Communication with TCM', description: 'The engine computer cannot communicate with the transmission control module.', symptoms: ['Transmission in limp mode', 'Erratic shifting', 'Transmission light on'], causes: ['Faulty TCM module', 'CAN communication problems', 'Damaged wiring', 'Blown fuse'], solutions: ['Check the TCM fuses', 'Inspect the module connectors', 'Diagnose the CAN bus', 'Test the TCM module'] },
  { code: 'U0102', title: 'Lost Communication with Transfer Case Module', description: 'Communication problem between the ECU and the ABS module.', symptoms: ['ABS light on', 'Abnormal ABS braking system'], causes: ['Open CAN bus', 'Faulty ABS module'], solutions: ['Check the CAN wiring', 'Check the ABS module'] },
  { code: 'U0103', severity: 'Crítica/No conducir', title: 'Lost Communication with Airbag (SRS) Module', description: 'The airbag system cannot communicate with the other modules.', symptoms: ['SRS light on', 'Airbags would not work correctly'], causes: ['Open CAN bus', 'Faulty SRS module'], solutions: ['Check the CAN wiring', 'Inspect the SRS module'] },
  { code: 'U0121', title: 'Lost Communication with ABS Control Module', description: 'The vehicle network lost communication with the ABS control module.', symptoms: ['ABS light on', 'Possible loss of ABS function', 'Stability light on'], causes: ['Faulty ABS module', 'CAN network problem', 'Blown fuse', 'Damaged wiring'], solutions: ['Check the ABS system fuses', 'Check the module power supply', 'Inspect the network communication', 'Test the ABS module with a scan tool'] },
  { code: 'U0122', title: 'Lost Communication with Stability Control Module', description: 'The electronic stability control (ESP) module cannot communicate.', symptoms: ['Stability light on', 'ESP system disabled'], causes: ['Open CAN bus', 'Faulty stability module'], solutions: ['Check the CAN wiring', 'Check the ESP module'] },
  { code: 'U0123', severity: 'Crítica/No conducir', title: 'Lost Communication with Steering Module', description: 'The electric power steering module cannot communicate.', symptoms: ['Heavy steering', 'Power steering light'], causes: ['Open CAN bus', 'Faulty steering module'], solutions: ['Check the CAN wiring', 'Check the steering module'] },
  { code: 'U0124', title: 'Lost Communication with HVAC Module', description: 'The A/C and heating system module cannot communicate with the network.', symptoms: ['A/C or heating does not work', 'Climate controls do not respond'], causes: ['Open CAN bus', 'Faulty HVAC module'], solutions: ['Check the CAN wiring', 'Check the HVAC module'] },
  { code: 'U0125', severity: 'Baja', title: 'Lost Communication with Lighting Module', description: 'The lighting module does not communicate.', symptoms: ['Lights do not respond'], causes: ['Open CAN bus'], solutions: ['Check the wiring'] },
  { code: 'U0126', title: 'Lost Communication with Steering Angle Sensor Module', description: 'The door module does not communicate.', symptoms: ['Doors do not respond'], causes: ['Open CAN bus'], solutions: ['Check the wiring'] },
  { code: 'U0127', severity: 'Baja', title: 'Lost Communication with Audio Module', description: 'The audio system does not communicate.', symptoms: ['Audio does not work'], causes: ['Open CAN bus'], solutions: ['Check the wiring'] },
  { code: 'U0128', title: 'Lost Communication with Power Seat Module', description: 'The power seat module does not communicate.', symptoms: ['Seats do not adjust'], causes: ['Open CAN bus'], solutions: ['Check the wiring'] },
  { code: 'U0129', severity: 'Baja', title: 'Lost Communication with Power Mirror Module', description: 'The power mirror module does not communicate.', symptoms: ['Mirrors do not adjust'], causes: ['Open CAN bus'], solutions: ['Check the wiring'] },
  { code: 'U0130', severity: 'Baja', title: 'Lost Communication with Wiper Module', description: 'The wiper module does not communicate.', symptoms: ['Wipers do not work'], causes: ['Open CAN bus'], solutions: ['Check the wiring'] },
  { code: 'U0150', title: 'CAN Communication Timeout', description: 'CAN communication wait time exceeded.', symptoms: ['Multiple codes', 'Slow communication'], causes: ['Congested bus', 'Low bus speed'], solutions: ['Diagnose the CAN speed'] },
  { code: 'U0155', title: 'Lost Communication with Instrument Cluster', description: 'The instrument cluster cannot communicate with the CAN network.', symptoms: ['Cluster off', 'No speed or RPM readings'], causes: ['Faulty instrument module', 'Open CAN bus'], solutions: ['Check the cluster fuse', 'Check the CAN wiring', 'Replace the module if needed'] },
  { code: 'U0164', title: 'Lost Communication with HVAC Control Module', description: 'The HVAC climate module cannot communicate.', symptoms: ['Climate control system inoperative'], causes: ['Faulty HVAC module', 'CAN bus problem'], solutions: ['Check the wiring', 'Replace the HVAC module'] },
  { code: 'U0168', severity: 'Crítica/No conducir', title: 'Lost Communication with Vehicle Control Module', description: 'The central vehicle control module cannot communicate.', symptoms: ['Multiple systems not responding'], causes: ['Faulty VCM module', 'CAN bus error'], solutions: ['Diagnose the CAN bus', 'Replace the VCM module'] },
  { code: 'U0200', title: 'Lost Communication with Door Lock Module / Data Integrity', description: 'The data transmitted over the CAN bus contains errors or is corrupt.', symptoms: ['Multiple erroneous codes', 'Erratic system operation'], causes: ['Electromagnetic interference', 'Damaged CAN wiring', 'Faulty ECU'], solutions: ['Check the CAN wiring', 'Look for interference sources', 'Check all ECUs'] },
  { code: 'U0300', title: 'Internal Control Module Software Incompatibility', description: 'Flash memory write timeout exceeded.', symptoms: ['Check Engine light', 'Programming problems'], causes: ['Faulty programming', 'Faulty ECU'], solutions: ['Reprogram the ECU'] },
  { code: 'U1000', title: 'Manufacturer-Specific Communication Fault', description: 'Manufacturer-specific communication code. Indicates a problem in a proprietary communication network.', symptoms: ['Varies by manufacturer', 'Possible multiple warning lights'], causes: ['Faulty proprietary module', 'Manufacturer communication bus problem'], solutions: ['Consult the manufacturer documentation', 'Scan with brand-specific equipment'] },
];
